### ISSUE TITLE
Show Notes ⚡️📻 10/19 @ Downtown LA

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#100]
## Stand Up
- 🎃  **Wrap Up:** On Sunday, we hung out with @codelaboc in Fullerton and worked on a lot of Hoodie pull requests. We updated README.mds, wrote specs and continued improving the [Hoodie Offline Tutorial](https://camp-tutorial.hood.ie/) site. Thanks @codelaboc and ProDeskSpace for the beautiful space and thanks to City of Fullerton for free parking 🚗 Read more about it: https://github.com/fullstackla/pairing-meetup/blob/master/notes/hacktober_2016.md 
- 🎊 *_Shout out *_ to all those who have been going through the tutorial to make it better for all. Y'all made it in [Hoodie's newsletter](http://us4.campaign-archive2.com/?u=12d36bbe9418ed6a43127cd62&id=f4c6b03dc8&e=9f16dbc657)! 💌  Look at our changes so far from @nosajong @jimthoburn @kkchu791 @Taekyoon @IanDCarroll @Janatbek 

![screenshot 2016-10-19 11 33 41](https://cloud.githubusercontent.com/assets/3673236/19532283/edeacc9c-95ef-11e6-8ff0-7964d4479135.png)
![screenshot 2016-10-19 11 33 50](https://cloud.githubusercontent.com/assets/3673236/19532281/ede3a0ca-95ef-11e6-94d0-4c536172688f.png)
- **Refactor of the Week:** https://github.com/hoodiehq/hoodie-camp-tutorial/pull/35/files _What do you think about this renaming of a method?_
## 🗓  Upcoming
- **This Friday:** SCNA @ USC http://scna.softwarecraftsmanship.org/
- This **Saturday**: Code Retreat @ 8th Light - Talk to @kpearson about volunteering
- This **Saturday**: Rails Girls @ Spokeo - Talk to @machikoyasuda about it if you're interested
- @jsla **lunch.js**: Find a lunch near you - https://github.com/jsla/lunch.js/issues
- More Saturday coding in LA: [LA Code & Coffee](https://twitter.com/lacodeandcoffee) 💻 ☕️  with @zacholauson

> ProTip: Don't see your event here? Looking for a carpool buddy to one of the events here? Comment below.
## :zap: We got issues:

> **Just for First Timers**
- Update README.md https://github.com/hoodiehq/camp/issues/80

> **Git practice** Practice a new Git and GitHub workflow: 
- Practice resolving merge conflicts via command line: https://github.com/jdorfman/awesome-json-datasets/
- Practice reviewing pull requests: https://github.com/hoodiehq/hoodie-camp-tutorial/pulls 

> **Writing specs**: Write some specs in JavaScript to test HTTP requests/responses:
- https://github.com/hoodiehq/camp/issues/75 
- https://github.com/hoodiehq/camp/issues/74 
- https://github.com/hoodiehq/camp/issues/73 
- https://github.com/hoodiehq/camp/issues/72
## 🛠 Tool of the month: ✨ Linting & Style Guides ✨

Have you ever used a Linter? Read a Code Style Guide? Check out Hoodie's to help you get onboarded to the Hoodie codebase: https://github.com/hoodiehq/hoodie/blob/master/CODING_STYLE.md
## Attendees:
1. @kpearson 
2. @leighphan 
3. @gr2m 
4. @jdorfman 
5. @reyesr3 
6. @jaimemendozadev 
7. @Janatbek
8. @IanDCarroll
9. @Taekyoon
10. @jimthoburn
11. @machikoyasuda
12. @justinjyoo
13. @blackcathacker 
14. @jcblw
15. @emilyyutschmidtling 
16. @SamNazar
17. @RobertKim
18. @simonyangme 
19. @xuhdev 
## Pull Requests
1. \- https://github.com/hoodiehq/hoodie-account-server/pull/206
2. \- https://github.com/hoodiehq/hoodie-account-server-api/pull/21
3. \- https://github.com/hoodiehq/hoodie-account-server/pull/208
4. \- https://github.com/hoodiehq/hoodie-account-server/pull/205
5. \- https://github.com/fullstackla/pairing-meetup/pull/102
6. \- https://github.com/fullstackla/pairing-meetup/pull/101
7. \- https://github.com/fullstackla/pairing-meetup/pull/106

**Comment by gr2m** [comment]
issues from Hoodie: https://github.com/hoodiehq/camp/issues?q=is%3Aopen+is%3Aissue+label%3A%22up+for+grabs%22

See you later 👋

**Comment by gr2m** [comment]
also please add yourself to our community :) https://github.com/fullstackla/pairing-meetup/tree/master/community and comment below with the things you have done and with whom you paired :)

**Comment by jdorfman** [comment]
@machikoyasuda here is the screencast of merging conflicts with a CLI: https://cl.ly/2i0R1s1L2O0Y

Update: Fixed 8 merge conflicts

**Comment by reyesr3** [comment]
@justinjyoo worked together on the [Create License issue](https://github.com/hoodiehq/pouchdb-users/pull/9)

**Comment by gr2m** [comment]
Today I helped people to contribute to Hoodie and made a video tutorial on how to add yourself as a Fullstack LA community member: https://dl.dropboxusercontent.com/u/732913/fullstackla-community-screencast.mov :)

**Comment by Taekyoon** [comment]
@Taekyoon @jimthoburn ⚡️ we work together here! https://github.com/hoodiehq/camp/issues/58

**Comment by blackcathacker** [comment]
@jaimemendozadev and I worked and submitted a PR for https://github.com/hoodiehq/camp/issues/73 and started to work on https://github.com/hoodiehq/camp/issues/74.
