### ISSUE TITLE
Show Notes ⚡️📻 10/27 @ Santa Monica

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#111]
## Stand up

> **Wrap up of Hacktober**: Fullstack has a super full October. We had 4 weekday meetups in Downtown LA, Downtown Santa Monica, and 3 weekend events (@codelaboc in Fullerton with @leighphan and @kangashley, SCNA with 8th Light, and Rails Girls LA at Spokeo, featuring many Fullstack contributors as coaches). 
> 
> Thank you especially to all that came, coded, carpooled, baked goodies and contributed! 🎃 🎃 
## This week's picks
- 📋  **Open source thing of note** by @tdreitz - LA job resource & Slack groups list https://github.com/tdreitz/Los-Angeles-Job-Search-Resources
- 🗓  **Event pick**: Nov. 1st with @jsla **lunch.js**: Find a lunch near you - https://github.com/jsla/lunch.js/issues
## Tonight's show: Introducing ✨ Concourse Continuous Integration
- The webpage is shiny: https://concourse.ci/
- The code is written in Go: https://github.com/concourse/concourse
- The documentation starts here: https://concourse.ci/setting-up.html
- The tasks are here in Trello: https://trello.com/b/FuLJO3yk/concourse
- Invitation to the tasks: https://trello.com/invite/b/FuLJO3yk/b1da33711b2ef0675e3d6457e12cdccd/concourse-ci
## Attendees:
1. \- @pivotaljohn 
2. \- @kpearson 
3. \- @karampok 
4. \- @zachgersh
5. \- @machikoyasuda
6. \- @jendiamond
7. \- @lawlessghost
8. \- @aoushana
9. \- @Taekyoon 
10. \- @bingr001
11. @jtigger
12. @MalcolmGC
## In Progress

![screenshot 2016-10-27 12 11 19](https://cloud.githubusercontent.com/assets/3673236/19781541/835fd1ec-9c3e-11e6-8091-aff6a4d21653.png)
## Pull Requests
1. https://github.com/concourse/git-resource/pull/90
2. https://github.com/concourse/s3-resource/pull/57
## Retro
1. Try Elm & work on: https://github.com/concourse/atc
2. Learn about SSL, S3

**Comment by machikoyasuda** [comment]
@kpearson Can we pair on this outstanding @exercism at next week's till we figure it out?

https://github.com/exercism/exercism.io/pull/3096

This has been open since the beginning of the summer!

cc / @jendiamond

**Comment by tyler-reitz** [comment]
thanks for the shoutout @machikoyasuda !!

**Comment by machikoyasuda** [comment]
Tagging @aoushana  - RSVP here http://www.meetup.com/la-fullstack/

**Comment by IanDCarroll** [comment]
Sorry I can't be there. Submit an extra PR for me! :jack_o_lantern: get a t-shirt!

**Comment by IanDCarroll** [comment]
Hey... is that date right? Or is FullStack Santa Monica on Thursday?

**Comment by jtigger** [comment]
@IanDCarroll date was off-by-one... clearly some programmer did it. ;)  Missed you last night!

**Comment by jtigger** [comment]
While not our golden delivery PR, @MalcolmGC and I submitted an adjustment to the readme (his first!): https://github.com/concourse/s3-resource/pull/57

**Comment by machikoyasuda** [comment]
@kpearson who was your pair? what did you work on?

**Comment by machikoyasuda** [comment]
@zachgersh @jtigger hi zac & john, did any other PRs get merged/pushed up from the other week?

Also, do you remember any other github handles of attendees?

Ps... Go is GOAT 🐐

**Comment by jtigger** [comment]
@machikoyasuda I didn't see any other PRs go through.  I didn't collect github nicks.
