### ISSUE TITLE
A GitHub repository tracking page for LA meetup groups' active projects that need/want help/users

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#116]
#### User Story

As a meetup enthusiast that can't attend every meetup,
I want a dynamic page that shows me the latest commits / issues on repositories created/added by meetup organizers,
so that I can keep track of the projects made by @MaptimeLA, @HackforLA, @FullStackLA, @CodeLabOC, @RailsGirlsLA and any other meetups in this area that has active open source contribution potential.
#### Current Behavior

Right now, I click Follow on any active LA coding meetup organizer/prolific open-source project maker and individually follow their repositories, issues, pull requests. I'm in 5+ different Slack groups for LA area coding groups and I can't join anymore. This is however, not sustainable.

![screenshot 2016-10-20 17 01 55](https://cloud.githubusercontent.com/assets/3673236/19582118/f4c05698-96e6-11e6-9c20-ef7ff4a36f30.png)
#### Inspiration

I want something like what @ChiHackNight meetup has created for repositories created by different groups in LA: https://chihacknight.org/open-source-projects.html. Except I want there to be more focus on Issues and where this group meets up physically in person. 

@ChiHackNight made and uses:
- That open source page https://github.com/chihacknight/chihacknight.org/blob/master/open-source-projects.html
- https://github.com/chihacknight/civic-json-worker `Python` Flask app that connects to GitHub API

---

[Made at Fullstack LA](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by machikoyasuda** [comment]
I would add a repositories from regularly-meeting groups (@hackforla) like this https://github.com/hackforla/project-groups from @ninakin, I would also add bigger projects like the LA Buildings Data Import (@MaptimeLA) to it https://github.com/osmlab/labuildings/issues

**Comment by machikoyasuda** [comment]
I would also add smaller individual libraries like @jcblw's LA Metro API https://github.com/jcblw/lametro-api 

I would also add OSS projects released by LA companies (LA Times - @datadesk) https://github.com/datadesk/latimes-calculate (KPCC - @scpr) and LA area governments.

Of course we can also always expand to places like Ventura County and Orange County too :)

**Comment by ryanponce** [comment]
Yo, I got this.

**Comment by machikoyasuda** [comment]
Yay for the enthusiasm Ryan. Lets all interest contributors sit down to wireframe, write a few user stories (tasks) and break it down into issues. Then we will ~~ pair ~~ up into twos and work on them together. Santa Monica next week!!

On Fri, Oct 21, 2016 at 4:49 PM -0700, "Ryan Ponce" notifications@github.com wrote:

Yo, I got this.
