### ISSUE TITLE
Add a .editorconfig and plugin installation instructions

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#117]
#### User Story

As a person who gets to merge Pull Requests on `.md` files with trailing whitespaces,
I want an `.editorconfig` file and everyone to install the necessary code editor plugins,
so that everyone's `.md` files are free of trailing whitespaces and indentation differences.
#### Context

I was reading the README for @reactioncommerce's (documentation)[https://github.com/reactioncommerce/reaction-docs] and noticed the `.editorconfig` file and I wanted one too!!!!!! Their docs are nice to read and browse: https://docs.reactioncommerce.com/reaction-docs/master/intro 

---

[Made at Fullstack LA](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by gr2m** [comment]
> so that everyone's .md files are free of trailing whitespaces and indentation differences.

I would not recommend that. If you want a line break like this
- **first line**  
  second line

then you need two spaces after the first line

```
- **first line**  
  second line
```

I even have that as an exception in my `~/.editorconfig`

```
[*]
end_of_line = lf
insert_final_newline = true
indent_size = 2
trim_trailing_whitespace = true
[*.md]
trim_trailing_whitespace = false
insert_final_newline = false
```

**Comment by machikoyasuda** [comment]
@gr2m ah! interesting.

what about just adding it for indentation differences?

**Comment by gr2m** [comment]
I’d be careful with adding to many `.confgXYZ` files to repositories. Usually it’s the maintainers who want them but very quickly a repository can be full of them and it makes things more complicated for new contributors. We try to limit them to the absolute minimum at Hoodie for that reason. When people submit a pull request you can review the styling and ask for changes, or just fix it yourself. If people keep contirbuting, they will know next time

**Comment by xuhdev** [comment]
How about creating one in the wiki page so people who use it can download and put it in the correct place? Though I don't see adding DOT files in the repo as an issue: people who don't use them can just ignore them -- they are not shown in `ls` any way.

**Comment by xuhdev** [comment]
EditorConfig also has a lot of issues unfixed. This also creates another venue to contribute. (Using open-source software is the motivation to contribute)

**Comment by machikoyasuda** [comment]
<3 <3 <3 
closing this for the time being
<3 <3 <3
