### ISSUE TITLE
📅❄️ FULLSTACK IRL WINTER BREAK IS COMING.

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#122]
### End of 2016:
- Last Downtown 🏙 meetup: Nov 30th 
- Last Santa Monica 🌴 meetup: Dec 7th
### Start of 2017:
- First Santa Monica 🌴 meetup: Jan. 11
- First Downtown 🏙 meetup: Jan. 18  
  (This looks incorrect but is accurate due to the new logic, see below)
### 2017 schedule logic:
- Downtown 🏙: on the 1st and 3rd Wed.
- Santa Monica 🌴: the other ones

```
if wednesday_count.odd?
  location = Downtown
else
  location = Santa Monica
end
```
### ❄️ Winter Break 2016 ❄️
1. Try remote pair programming. 
2. Write a method in any language of your choice that will return East or West when asked, `Which side?` and it will know where Fullstack is that week. It can be on Command Line, JavaScript console, LED lights, a website, whatever.

**Comment by kpearson** [comment]
### 📆  Fullstack calendar
- Google calendar link:
  https://calendar.google.com/calendar/embed?src=lh8vmi75156u0gs1lfoit346r8%40group.calendar.google.com&ctz=America/Los_Angeles
- Subscribe link: https://calendar.google.com/calendar/ical/lh8vmi75156u0gs1lfoit346r8%40group.calendar.google.com/public/basic.ics
