### ISSUE TITLE
Should we have a meetup the Wednesday before Thanksgiving?

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#124]
Respond in Emojis, thumbs up or down:

**Comment by machikoyasuda** [comment]
@pivotaljohn @kpearson Should we have a Fullstack at Pivotal the Wed. before Thanksgiving? The car traffic might be terrible.

**Comment by IanDCarroll** [comment]
If you got no family nearby :bowtie: otherwise: :sweat: 
I'm more worried that the Organizers will burn themselves out

**Comment by machikoyasuda** [comment]
Seems like it's decided: We are not going to have a meetup at Pivotal the Wed. before Thanksgiving.

I'm gonna be hunkering down at my computer waiting for Black Friday to blow up my work servers :)  ... so Wed-Before-TG 🦃  is hard for me too.

**Comment by machikoyasuda** [comment]
@kpearson lets cancel the meetup Wed. before TG!!!
