### ISSUE TITLE
✨Your First Project✨ Who wants to learn HTML/JS to make a beautiful site for our community members?

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#125]
#### User story

As a avid meetuper/organizer/person-who-likes-to-make-things-happen,
I want to see all of these people's self-written stories,
so I can learn people's names & stories & origins better.... and I can teach someone how to make use JavaScript to make an AJAX request to the GitHub API to make this site happen for reals.

#### Sketch it out

Someone wanna sketch a wireframe out of this on paper?
#### Assign
- Project Filler Outer https://github.com/fullstackla/pairing-meetup/projects
- Wireframe Sketch Pairs
- HTML/JS Pairs
  ...
## Who wants to collaborate on their first group IRL project?

[Made at Fullstack](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by gr2m** [comment]
here is a simple prototype to load the profiles directly from GitHub
https://github.com/gr2m/github-community-list

**Comment by machikoyasuda** [comment]
Forked here http://github.com/kevinpagtakhan/github-community-list/commit/a17eaea70fb3e05b6cc23e21b64b37f22a48c2d0

**Comment by machikoyasuda** [comment]
Look what we have so far here: https://gr2m.github.io/github-community-list/

Tasks now:
- HTML/CSS/design ideas
- Cache the API
- Write a spec that tests that each MD file has a # H1 header
