### ISSUE TITLE
💯 Write funner, better culturally-relevant, mind-expanding, interesting Exercisms 🗓

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#126]
### User story

As a **person who appreciates non-Western date formats**,
I **want to come up with an excuse to write code in different languages**,
So I **wrote this issue to intrigue Fullstack-ers**:
### Exercism problem submission idea:
- Write a problem that asks the user to turn a Western year format (e.g. 2012) into a Japanese format (平和　２６）and other non-Western formats.
### Start:
- https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#implementing-a-completely-new-exercise

[Made at Fullstack](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by IanDCarroll** [comment]
I've played with this idea before: worked on Traditional Chinese DateTime (https://github.com/IanDCarroll/TemporalConverter). I suppose I could write a test script for someone to code against...
