### ISSUE TITLE
Should we go to OWASP meetup? Open source security meetup

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#133]
What is SSL?

idunno

Should we go? Who wants to carpool?

http://www.meetup.com/OWASP-Los-Angeles/events/227924004/

**Comment by machikoyasuda** [comment]
@server-monitor have you ever been to http://www.meetup.com/OWASP-Los-Angeles/ ?

**Comment by kangashley** [comment]
Came across OWASP today, too! Count me in 🙋🏻

**Comment by server-monitor** [comment]
@machikoyasuda no I haven't. Looks interesting.

**Comment by pmbanugo** [comment]
go take a look @machikoyasuda i think you'll come out with some new perspective

**Comment by rouzbeh84** [comment]
so no go? looks pretty interesting haha
