### ISSUE TITLE
✨Your First Design/UX/Product Meeting✨ How can we improve the onboarding first page of Exercism.io?

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#135]
As a first-time web newbie who has never used or heard of GitHub.com before, 
I get intimidated and confused when Exercism.io demands that I log in Via Github.
I wish the first onboarding page of Exercismio explained how fun Github is,
before I sign up.

What are some illustrations,
design patterns,
colors,
font schemes,
text,
gifs,
animations,
screenshots,
screenshot gifs,
beautiful-shit-there-ain't-no-word-yet
we can use
to make this less scary?

Design meeting lead: @leighphan (or who else? is into this stuff)?
Branding lead: SUSIE!!

**Comment by machikoyasuda** [comment]
@jtigger https://github.com/exercism/exercism.io/projects/1

Hey @jtigger, at Fullstack Downtown, we will be workshopping this exact question tonight. Or maybe in December. Maybe we can do this at Pivotal Labs in December in SaMo.

**Comment by machikoyasuda** [comment]
Somewhat related: Here's a new issue we can work on https://github.com/exercism/exercism.io/issues/3228

We can then watch first-time Exercism contributors people read the CONTRIBUTING.md

Then we can suggest suggestions to https://github.com/exercism/exercism.io/projects/1 to improve the Documentation.

And thennnn someone can add the TEAM STREAM url in the nav bar, so I can get to it faster, so I can nitpick more people from our Fullstack team, and continue to make Exercism awesomer faster.

**Comment by jtigger** [comment]
@machikoyasuda the scenario of a new Exercism user who does not already have a GitHub account is particularly challenging.

I believe the GitHub sign-up flow intends to get the user back to where they came from once that person completed the account creation; but that wasn't my experience (I tried out that flow yesterday morning for research on a separate issue).  Instead, I got stopped at the point where I was supposed to verify my email address.  When I clicked the link in that email, I just got dumped at GitHub's homepage (i.e. not returned to Exercism) 😦 

I know that's not the only speedbump here, but it's a particularly mechanical one.

I'm fascinated to hear how that workshop went!  If it didn't happen last night, then yeah would love to do it next week in SM.

**Comment by machikoyasuda** [comment]
Reopening this issue for consideration as a Fullstack project for people interested in:
- learning how to conduct UX user experiements
- learning how to lead a design meeting, a product meeting
- learning how to talk to product owners/open source maintainers
- learning how to work on your first Front-End task for a open source project

CC @leighphan

**Comment by leighphan** [comment]
+1! Learning how to use exercism.io *and* GitHub for the first time last year, I personally encountered this confusion and observed it in others' experiences too.

I'm all for adding some kind of quick demo of what GitHub is + how it works + why it's awesome. Showing > telling. Maybe a video clip? Of course GitHub takes a little practice to get used to, but a high-level demo could work. :nerd_face:

**Comment by machikoyasuda** [comment]
closing this for now
