### ISSUE TITLE
Step 1, Being a client in a branding meeting. Getting branded.

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#136]
#### User story
As a developer/meetup organizer who really wants pretty visuals but can't quite find the words for it,
I need to make a list of all the assets we need from a design,
so that we know what dimensions we are working with.

### "Deliverables"
1. List of all assets needed in what formats (jpg, png, gif), and what dimensions (square or rectangle)
2. List of inspirational websites we like.
3. List of stuff we want.

#### Pairing

paired with @kpearson  & @xyzzyismagic

---

[Made at Fullstack](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by machikoyasuda** [comment]
# List 1: Visual Requirements

### GRAPHICS, SQUARE
1. GitHub icon
2. Twitter icon
3. YouTube icon

### GRAPHICS, RECTANGLEY
1. Twitter banner
2. YouTube banner
3. Meetup banner

### MOTION GRAPHICS, RECTANGLEY
1. YouTube title page

# List 2: Stuff that makes us ✨⚡️
- Machiko: 
- Kit @kpearson: List URLs you like here

# List 3: "Deliverables"

### What we want
1. E-mail newsletter sign-up situation, like http://compiler.la/'s 
2. Font face combos (Free-r the better, easy to read for people from all sorts of countries where English is not their first language, for people who may be color blind, for people who may have reading issues)
3. Color combos (HEX, RGBA) (Color-blind safe color combos preferred)
4. Icons for complex complicated concepts, like, "meetup" https://thenounproject.com/

**Comment by machikoyasuda** [comment]
@kpearson put your Internet Inspirational pages/links/color combos/typefaces you like here please!

Also you can put stuff you do NOT like too.

**Comment by xyzzyismagic** [comment]
@machikoyasuda @kpearson 

Are ya'll asking me to brand your meetup or for advice/perspective on how to communicate your needs in a brief meant for a designer?

**Comment by machikoyasuda** [comment]
@xyzzyismagic Both. 

We are devs learning how to talk ~design~, in an open source way (aka doing it in the Public, not in Private Emails or Private Places that No One Else Can Learn From.)

**Comment by machikoyasuda** [comment]
@xyzzyismagic kinda like the StartUp Podcast, the Podcast About Starting a Podcast Company. Or something meta like that.
