### ISSUE TITLE
Show Notes ⚡️📻 11/9 @ Santa Monica

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#137]
## Stand up
- **Shout out** to @jcblw && @blackcathacker from last week's downtown meetup for ⛵️-ing a Team menu bar link on Exercism.io's homepage. Check it out live: http://exercism.io/

![screenshot 2016-11-08 10 18 13](https://cloud.githubusercontent.com/assets/3673236/20111314/bb29e8e4-a59c-11e6-8551-2cbefc70fcd0.png)

We tested it, and the Team names are emoji-compatible. 

- **Last week's Santa Monica show**: At last week's Santa Monica show, sponsored by Pivotal Labs & hosted by @exercism_io maintainer @pivotaljohn / @jtigger , our favorite local [Rubyist-turned-Go-langer](http://zachgersh.github.io/) 🐐 @zachgersh (DBC '13 alumni) showed us the ropes of continuous integration, a code deploying tool from Pivotal. We worked on things like Go, S3, and more acronyms. Check out last week's show notes for more: https://github.com/fullstackla/pairing-meetup/issues/111

- ** STAND UP QUESTION OF THE DAY ** : What is the last open-sourced thing you used today?

> ProTip: Have you joined our http://exercism.io/teams/dtla-pair-programming/ group yet? Have you set it as your homepage yet? 

- 📅 Fullstack Winter Break: https://github.com/fullstackla/pairing-meetup/issues/122

## This month's picks
- 📋  **Indie LA Open Source pick** by @zenorocha - Add this on your website input fields: clipboard.js https://github.com/zenorocha/clipboard.js/
- 🌴 **Corporate LA Open Source pick** by @dollarshaveclub - https://dollarshaveclub.github.io/shave/ They have issues: https://github.com/dollarshaveclub/shave/issues/10 They also have job openings.
- Are you in job-hunting mode? https://github.com/fullstackla/pairing-meetup/issues/129

## Question of the month: Do you rent in LA? Do you know if your apartment is under rent control?
- Check out this open source map by @theworksla http://cityhubla.github.io/LA_Building_Age/#12/34.0267/-118.2621

## Where to start:
1. Completely new to coding? Start by pairing on Exercism puzzles!
2. First Timers Only: New to contributing to applications/projects: https://github.com/fullstackla/pairing-meetup/issues/127 https://github.com/fullstackla/pairing-meetup/issues/125 https://github.com/fullstackla/pairing-meetup/issues/127 https://github.com/fullstackla/pairing-meetup/issues/125 https://github.com/fullstackla/pairing-meetup/issues/130 https://github.com/exercism/exercism.io/issues/3228#issuecomment-257933565
3. I want to try Go: https://github.com/fullstackla/pairing-meetup/issues/1
4. I am itching to work on a group project but I don't have ideas or friends to start one with: https://github.com/fullstackla/pairing-meetup/issues/134 https://github.com/fullstackla/pairing-meetup/issues/125 https://github.com/fullstackla/pairing-meetup/issues/126

## Contributors + stuff you want to work on:
- http://www.meetup.com/la-fullstack/events/234936848/

1. - @machikoyasuda https://github.com/pouchdb/pouchdb/issues/5814#issuecomment-256796333 
2. - @gr2m 
3. - @Taekyoon 
4. - @kpearson 
5. - @desireedesario
6. - @jarekjar
7. - @jendiamond 
8. - @bingr001
9. - @lawlessghost
10. - @pivotaljohn 
11. - @jimthoburn 
12. - @IanDCarroll 
13. - @arunkhanna00
14. - @kevinpagtakhan

**Comment by machikoyasuda** [comment]
@jtigger @pivotaljohn 

I have made special First Timer's Only exercism issues & challenges:

https://github.com/fullstackla/pairing-meetup/issues/127

https://github.com/fullstackla/pairing-meetup/issues/126

**Comment by jcblw** [comment]
Just wanna say @blackcathacker helped out quite a bit with that PR 🙌 pairing FTW

**Comment by machikoyasuda** [comment]
hi @arunkhanna00 - were you working on the community page yesterday? would you mind pushing up that repository somewhere on github so others can take a look and help out? <3

**Comment by machikoyasuda** [comment]
@kpearson can you add any other github handles of other contributors from yesterday?

**Comment by akhanna00** [comment]
Hmm, I'm pretty sure @kevinpagtakhan pushed it...

**Comment by machikoyasuda** [comment]
@arunkhanna00 @kevinpagatkhan @gr2m and i merged y'alls CSS changes and picked it up from there: https://gr2m.github.io/github-community-list/
