### ISSUE TITLE
Create a timeline & map of Meetup Organizing in LA

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#141]
#### User story

As a newbie to the LA tech community,
I want to see a timeline of the tireless work of organizers here,
so I can get a better sense of the badass community that is here.

#### Started

- Here https://github.com/fullstackla/pairing-meetup/blob/master/squad/timeline.md
---

[Made at Fullstack](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by machikoyasuda** [comment]
@jendiamond What year did RailsBridge happen?

What year did LA Ruby Women start?

**Comment by machikoyasuda** [comment]
@learningnerd What year did you start Learn to Code LA? Did I get it right?

**Comment by machikoyasuda** [comment]
@leighphan hey look leigh - i'm recounting the history of LA organizing :) eventually this will turn into a timeline/map/list of people/faces.

**Comment by LearningNerd** [comment]
@machikoyasuda Jan 31st 2015 :)

**Comment by machikoyasuda** [comment]
Updated: https://github.com/fullstackla/pairing-meetup/blob/master/squad/origins.md

**Comment by server-monitor** [comment]
Timeline you say? I made a small app graphing the timelines/Yes RSVPs of a few of LA's most awesome meetups.

https://server-monitor.github.io/timelines/

**Comment by machikoyasuda** [comment]
@server-monitor OMG!

**Comment by machikoyasuda** [comment]
@server-monitor how did you make that? why's the javascript all minified and unreadable?

**Comment by server-monitor** [comment]
@machikoyasuda It defaults to gh-pages branch, the build branch. There's a master branch which contains source, which is a mess and not that different from the minified version :)

I used create-react-app to create this. As far as I know, the only way to run this app locally is to create an app using create-react-app, clone the repo, copy the repo files into the newly created create-react-app app, `npm install` dependencies (determined by checking the differences between the `package.json` files, then lastly, run `npm start`. 

It's broken currently though. I didn't realize that CORS only works on meetup.com on apps using OAuth. I'll try to implement OAuth later.

Happy Thanksgiving.
