### ISSUE TITLE
Show Notes ⚡️📻  1/11 @ 8th Light Downtown

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#149]
## Stand up

> ProTip: New to Fullstack? Check out our member directory and add yourself to the list: https://github.com/fullstackla/pairing-meetup/blob/master/community/README.md
- How should we improve this page? How can we open source and share this project so other meetup groups can make pages like this of themselves?

> ProTip: Is your 2017 resolution to code more katas? Try a different language? Join our Exercism team http://exercism.io/teams/dtla-pair-programming/ Set it as your desktop homepage.

## Open source picks!
- @gr2m wrote a sauce labs thing: https://github.com/gr2m/selsa
- @cityhubla digs into LA data and maps it: https://cityhubla.github.io/lacity_exploration_12/#13.08/34.1389/-118.2547

## Where to start:
1. Completely new to coding? Start by pairing on Exercism puzzles.
2. First Timers Only: New to contributing to applications/projects: 1) https://github.com/fullstackla/pairing-meetup/issues/127 2) https://github.com/fullstackla/pairing-meetup/issues/125 3) https://github.com/fullstackla/pairing-meetup/issues/127 4) https://github.com/fullstackla/pairing-meetup/issues/125  5) https://github.com/exercism/exercism.io/issues/3228#issuecomment-257933565
3. I want to try Go: https://github.com/fullstackla/pairing-meetup/issues/1
4. I am itching to work on a group project but I don't have ideas or friends to start one with: https://github.com/fullstackla/pairing-meetup/issues/134 https://github.com/fullstackla/pairing-meetup/issues/125 https://github.com/fullstackla/pairing-meetup/issues/126

## Contributors + stuff you want to work on:
- Attendees: https://www.meetup.com/la-fullstack
- @kpearson 
- @machikoyasuda - I am going to work on the webpage that shows the Fullstack 2017 schedule. I will write some code to calculate directions, show parking info, show Metro info, all sorts of fun stuff.
- @dopatraman - I'll be working on a slackbot that can order pizza

**Comment by dopatraman** [comment]
@dopatraman - I'll be working on a slackbot that can order pizza

**Comment by xuhdev** [comment]
For any new contributors: There is a typo in the [fullstack LA code of conduct](https://github.com/fullstackla/fullstackla.github.io/blob/master/code-of-conduct.md): The word "religion" should be in the sublist of " + offensive verbal comments related to".

**Comment by machikoyasuda** [comment]
https://github.com/fullstackla/fullstackla.github.io/pull/45 hi @xuhdev we missed you a lot

**Comment by xuhdev** [comment]
hi @machikoyasuda gonna be there today!

**Comment by machikoyasuda** [comment]
@dcmoore & @xuhdev & i paired on these commits in Clojure:
https://github.com/dcmoore/resilient-integration-workshop/commit/65e2143bc809324f8e71b3d85fd4a4a655e01520

https://github.com/dcmoore/resilient-integration-workshop/commit/8d5b114620236e1f6d16ca643a4b76523e4d822e

and i learned `git diff --cached`

and i learned you can change the git authors manually. doesn't show up on github though (yet)
