### ISSUE TITLE
Exercism & Pairing & Projects: Make a simple true/false questionaire

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#15]
Questions to ask:
- I have used command line
- I am comfortable using the command line: moving and changing directories, running files
- I have written code in a text editor (like Atom, Sublime Text)
- I have written a test and run it (examples: Rspec, Jasmine)
- I have written a function that takes in data and returns data (like a Ruby method or a JavaScript function)

Adding:
- I have a GitHub.com account
- I have used GitHub from the Terminal to clone repositories and push them up to GitHub.com
- I have used GitHub from the website or GUI app

@kpearson - Any other good questions to ask first-timers to get a gauge of their experience level?

**Comment by kpearson** [comment]
Questions about git and Github would give us insights, including the ability to setup and use the Exercism cli.
- I have a Github account
- I am comfortable using git to clone a repository form Github
