### ISSUE TITLE
Today's Fullstack ⚡️📻   Show Notes 2/1 @ Carbon 5

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#150]
## Stand up

> ProTip: New to Fullstack? Check out our member directory and add yourself to the list: https://github.com/fullstackla/pairing-meetup/blob/master/community/README.md
- How should we improve this page? How can we open source and share this project so other meetup groups can make pages like this of themselves?

> ProTip: Is your 2017 resolution to code more katas? Try a different language? Join our Exercism team http://exercism.io/teams/dtla-pair-programming/ Set it as your desktop homepage.

## Open source picks!
- @gr2m wrote a sauce labs thing: https://github.com/gr2m/selsa
- @cityhubla digs into LA data and maps it: https://cityhubla.github.io/lacity_exploration_12/#13.08/34.1389/-118.2547

## Where to start:
1. Completely `new to coding`? Start by pairing on Exercism puzzles.
2. Never made an open source Pull Request before? You're in the right spot -- Some issues for `First Timers Only`: New to contributing to applications/projects: 1) https://github.com/fullstackla/pairing-meetup/issues/127 2) https://github.com/fullstackla/pairing-meetup/issues/125 3) https://github.com/fullstackla/pairing-meetup/issues/127 4) https://github.com/fullstackla/pairing-meetup/issues/125  5) https://github.com/exercism/exercism.io/issues/3228#issuecomment-257933565
3. I want to try `Go`: https://github.com/fullstackla/pairing-meetup/issues/1
4. I am itching to work on a group project but I don't have ideas or friends to start one with: https://github.com/fullstackla/pairing-meetup/issues/134 https://github.com/fullstackla/pairing-meetup/issues/125 https://github.com/fullstackla/pairing-meetup/issues/126
5. Other great projects we've contributed to at this meetup: Homebrew (Ruby), Hoodie (JS), Exercism (Ruby, Go) and more here: https://github.com/fullstackla/pairing-meetup#zap-open-source-projects-we-have-contributed-to-at-the-meetup

## Contributors + stuff you want to work on:
- Attendees: https://www.meetup.com/la-fullstack
- @kpearson 
- @machikoyasuda - I am going to work on the webpage that shows the Fullstack 2017 schedule. I will write some code to calculate directions, show parking info, show Metro info, all sorts of fun stuff.

**Comment by dorachan2000** [comment]
[link to pull request!](https://github.com/exercism/exercism.io/pull/3370)

**Comment by dorachan2000** [comment]
test
[](https://github.com/exercism/exercism.io/pull/3370)
