### ISSUE TITLE
Show Notes ⚡️📻 3/1 @ Santa Monica - Pivotal Labs

### ISSUE THREAD

**Issue by dorachan2000** [fullstackla/pairing-meetup#151]
## Stand up
> 🍜  Eat lunch with us with @jsla https://github.com/jsla/lunch.js/issues - now in the [SF Valley](https://github.com/jsla/lunch.js/issues/36) thanks to Fullstack member @remarks, [Culver City x Playa Vista](https://github.com/jsla/lunch.js/issues/34) with @machikoyasuda and @jarrettch, and other locations: Downtown LA, Downtown Santa Monica.

> Open source meets UCLA, thanks to @gr2m: https://github.com/welcome-to-open-source/ucla#open-source-projects-and-issues-for-new-contributors 
## ⭐️ This week's picks
1. 🎵 Rad open project of the month: Ukulele chords by @jdobrowner + @mzarako https://jdobrowner.github.io/learn-ukulele/ at https://github.com/jdobrowner/learn-ukulele using https://github.com/Tonejs/Tone.js/
2. 🗺 Rad project from meetup fam @codelaboc: Stormwater Data Challenge map https://codelaboc.github.io/CA-Stormwater-Data-Challenge/

![screenshot 2017-02-27 12 24 15](https://cloud.githubusercontent.com/assets/3673236/23378266/ae40f9f4-fce7-11e6-84bc-64e544e00293.png)

### Did you know many LA companies have their own open source projects you can use and contribute to?
- Fullscreen, Playa Vista: https://github.com/Fullscreen/yt
- Dollar Shave Club, Playa Vista: https://github.com/dollarshaveclub/ 
- Liferay, Diamond Bar: Senna.js: https://github.com/liferay/senna.js

### First Time? Begin here:
- For your first Pull Request @ Fullstack: https://github.com/fullstackla/pairing-meetup/blob/master/community/README.md
- For coding puzzles: Join our Exercism team: http://exercism.io/teams/dtla-pair-programming/streams

## Attendees:
> Meetup Page: https://www.meetup.com/la-fullstack/events/237937106/
- @kpearson 
- @dorachan2000 

## Retro:

[Made at Fullstack](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by machikoyasuda** [comment]
some links to add from last week in LA's open source world:
- https://welcome-to-open-source.github.io/ucla/

some places to look for new issues in the LA open source world:
- js https://github.com/reactioncommerce/reaction/issues

**Comment by machikoyasuda** [comment]
Exercisms to check out and nitpick:
- hello world in clojure by @blackcathacker http://exercism.io/submissions/8dbf266ed780417c8b51d3979f164132
- check out the latest Ruby auto-nitpick on @kpearson's latest submission
http://exercism.io/submissions/ba352d6f3b9b40e5ac95cbffb1f67a86

- Are you in our Exercism team? http://exercism.io/teams/dtla-pair-programming/streams

**Comment by machikoyasuda** [comment]
cool project of the month: https://jdobrowner.github.io/learn-ukulele/

**Comment by machikoyasuda** [comment]
check out the latest @Hoodiehq newsletter! i spy @xuhdev @Taekyoon @jimthoburn and others: http://us4.campaign-archive1.com/?u=12d36bbe9418ed6a43127cd62&id=96f23dea01&e=e5b554431f
