### ISSUE TITLE
Show Notes ⚡️📻 4/5 @ DTLA - 8th Light

### ISSUE THREAD

**Issue by kpearson** [fullstackla/pairing-meetup#154]
#### User story

As a (     ),
I want (     ),
so that (     ).

#### Credits

* @kpearson

---

[Made at Fullstack](https://github.com/fullstackla/pairing-meetup) :zap:

**Comment by dcmoore** [comment]
https://github.com/Mashape/microservices/pull/1
https://docs.google.com/presentation/d/1lf46UqqFHo3XrgEjx_KDpUKRN1XWZbsfaK3JV8GXQ70/edit?usp=sharing
