### ISSUE TITLE
Show Notes 4/6 at 8th Light

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#157]
## first timers!!

@kevinkhuat
@byou7161
@schretzilla 

## returnees

@Taekyoon 
@jdorfman 
@chrisdobler
@blackcathacker
@dorachan2000

yay!!!!

**Comment by machikoyasuda** [comment]
@dcmoore what was that thing you were working on?

**Comment by machikoyasuda** [comment]
@bingr001 and @blackcathacker worked on https://github.com/Parrit/Parrit/pull/50

**Comment by dcmoore** [comment]
@machikoyasuda
Mashape/microservices#1
https://docs.google.com/presentation/d/1lf46UqqFHo3XrgEjx_KDpUKRN1XWZbsfaK3JV8GXQ70/edit?usp=sharing
