### ISSUE TITLE
Show Notes ⚡️📻   7/5 @ DTLA 8th Light

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#159]
## Stand up

> ProTip: New to Fullstack? Check out our member directory and add yourself to the list: https://github.com/fullstackla/pairing-meetup/blob/master/community/README.md
- How should we improve this page? How can we open source and share this project so other meetup groups can make pages like this of themselves?

> ProTip: Is your 2017 resolution to code more katas? Try a different language? Join our Exercism team http://exercism.io/teams/dtla-pair-programming/ Set it as your desktop homepage.

## Open source picks!
- @gr2m wrote a GitHub app tutorial for Node.js: https://github.com/gr2m/github-app-example

## Where to start:
1. Completely new to coding? Start by pairing on Exercism puzzles.
2. First Timers Only: New to contributing to applications/projects: https://www.codetriage.com/ http://up-for-grabs.net/#/ are good places to start.

## Contributors + stuff you want to work on:
- Attendees: https://www.meetup.com/la-fullstack
1. @kpearson - co-organizer
2. @machikoyasuda - co-organizer
3. @dcmoore - 8th Light host
4. @jaimemendozadev 
5. @learningnerd
6. @aroduribe
7. @jimthoburn 
8. @gaerphuoc
9. @imdoingotherthings
10. @mochajoe
11. @jvillama
12. @agonzalez0515
13. @arlene-perez
14. @ssbothwell
15. @nassirmz
16. @ransomw
17. @bean00

## Paired @ Fullstack 
- https://github.com/gr2m/github-app-example/pull/2 @arlene-perez 
- https://github.com/gr2m/github-app-example/pull/1 @arlene-perez
- https://github.com/fullstackla/pairing-meetup/pull/160 @aroduribe 
- https://github.com/gaerphuoc/Full-Stack-LA-8th-Light-Virtual-Pet @gaerphuoc
- https://github.com/gr2m/github-app-example/pull/4 @jvillama
- https://github.com/gr2m/github-app-example/pull/3 @jaimemendozadev

**Comment by gr2m** [comment]
Here are some good resources to find good Open Source projects / issues to work on

- http://www.firsttimersonly.com/
- http://up-for-grabs.net/
- https://twitter.com/first_tmrs_only
- https://twitter.com/yourfirstpr
- https://github.com/showcases/great-for-new-contributors
- https://github.com/MunGell/awesome-for-beginners

Other resources

- https://opensource.guide/
- https://opensourcefriday.com/

**Comment by samnags** [comment]
I paired with Liz on Exercism. Thanks for having me!

**Comment by LearningNerd** [comment]
Hey @samnags that was a great pairing session, good to meet you! :) Thanks @machikoyasuda and @kpearson for hosting!!
