### ISSUE TITLE
It's ok to not understand.

### ISSUE THREAD

**Issue by kennethlee** [fullstackla/pairing-meetup#16]
While observing newbies, I've sometimes noticed they tend to be pretty averse to asking questions, presumably, for fear of appearing unintelligent. For the same reason, they will also say that they understood an explanation despite being betrayed by their body language.

This is not a good thing.

I'm gonna mull over this for a bit and write up a doc for the wiki with some suggestions on things that we can do better to foster a "fear-free" environment.

**Comment by machikoyasuda** [comment]
It is also okay to not know the answer to a question someone just asked you. :)

**Comment by kennethlee** [comment]
Yep, of course. In which case we can figure out the answer together :computer:

**Comment by kennethlee** [comment]
I totally dropped the ball on this. :-1:

I have a rough draft going and will finish it/add it to the wiki by the end of the week.

**Comment by jendiamond** [comment]
Are you still doing this? It sounds super useful. :)

**Comment by kennethlee** [comment]
@jendiamond It's been a little while so I'm fuzzy on the details (note: I have a terrible memory), but I thought I did create a page for this in the wiki? I could be confusing another task for this one, though.

Anyway, feel free to take this task upon yourself if you'd like; otherwise, I'll try to make another write up by next week.

**Comment by machikoyasuda** [comment]
Hot unsolicited tips: 
1. Always post a link to the-thing-you-worked-on to the Issue page. Then no one will ever forget where/what happened.
2. As we all go along our code-learning journeys, if you come across even one lesson we the meetup organizers and attendees can learn from, it's perfectly 100% awesome to just post that one thing. We don't need long things. You can add one tip at a time!! Agile!!!

**Comment by kennethlee** [comment]
1. Yeah, failing to leave a link here to the finished piece was an oversight.
2. Good point. I'll create a page now and start it off with just a line or two.

**Comment by machikoyasuda** [comment]
You can make a PR to add a .MD file in our regular repo if you want!
Or  a wiki. Will eventually deprecate the wiki I think and just make people add MD files here instead.

**Comment by kennethlee** [comment]
Ok, I think this was it: 9f639ab. I also just added PR #44

I feel like we can further distill what's already there and add more to it.

**Comment by IanDCarroll** [comment]
This could be relevant to inclusivity:
 <a href="https://medium.com/@codepo8/things-not-to-say-on-stage-at-a-tech-event-178337b8c481#.yeme0f3gc">things not to say on stage at a tech event</a> 
reminds me of some things already talked-about.
