### ISSUE TITLE
Show Notes ⚡️📻   8/2 @ Santa Monica - Carbon 5

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#161]
## Stand up

> ProTip: New to Fullstack? Check out our member directory and add yourself to the list: https://github.com/fullstackla/pairing-meetup/blob/master/community/README.md
- How should we improve this page? How can we open source and share this project so other meetup groups can make pages like this of themselves?

> ProTip: Is your 2017 resolution to code more katas? Try a different language? Join our Exercism team http://exercism.io/teams/dtla-pair-programming/ Set it as your desktop homepage.

## Open source picks!
- @gr2m wrote a GitHub app tutorial for Node.js: https://github.com/gr2m/github-app-example

## Where to start:
1. Completely new to coding? Start by pairing on Exercism puzzles.
2. First Timers Only: New to contributing to applications/projects: https://www.codetriage.com/ http://up-for-grabs.net/#/ are good places to start.

## Open issues for `First Timers Only`:
- https://github.com/Esri/esri-leaflet/issues/980
- Write a test for p5.js: https://github.com/processing/p5.js/wiki/Development

## Contributors + stuff you want to work on:
- Attendees: https://www.meetup.com/la-fullstack
- first timers: @ipnicholson
- first timers: @sdillahey
- first timers: @outofambit

## Paired @ Fullstack

**Comment by jgravois** [comment]
thx @machikoyasuda! i'd be **happy** to help with <kbd>First Timers Only</kbd> questions!
