### ISSUE TITLE
Pairing & Projects: Who wants to pair on open source projects?

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#18]
I have issues brewing for this one: https://github.com/exercism/exercism.io

Instructions for set-up: https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md

**Comment by machikoyasuda** [comment]
Example: https://github.com/exercism/exercism.io/pull/2807

**Comment by kennethlee** [comment]
I'm down (my Ruby is getting pretty rusty, though).

**Comment by machikoyasuda** [comment]
Some instructions on getting set up to do so:
- https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md
- set up github exercism project on github.com
- fork
- clone fork
- cd into project
- bin/setup
- edit env
- rake db:reseed
- run server:  bundle exec foreman s -p 4567
- find/choose an issue to work on: https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md

Also useful:
- https://guides.github.com/activities/contributing-to-open-source/
- https://help.github.com/articles/syncing-a-fork/

How to write the perfect PR:
- https://github.com/blog/1943-how-to-write-the-perfect-pull-request
