### ISSUE TITLE
Pairing version 2.0

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#24]
### Same Focus:
1. Pair Programming
2. Agile Practices with real-world collaboration processes: Stand Up, Retros, MVPs, pairing, testing
3. Free & Open Source tools: Git, Atom, GitHub, projects
### Mission & Why?

We want people to practice carefully listening, observing others, talking to each other, teaching and learning from each other. Practice coding empathy through pairing, listening to each other at stand-ups and retros. We prefer to teach real free tools and processes developers commonly use, like free code editors, Git, GitHub, on open-source projects and tools, like Exercism. 
### Tracks:
1. Open Source Navigating - 1) read and find issues, 2) clone repos, install dependencies, run project locally, 3) tackle them together with a pair
2. Test-Driving - practice 1) running a test suite, 2) writing tests, 3) failing them, 4) passing them
3. Project-Driving/Navigating - 1) navigate a pair through your current open-source/public side-project, work on issues together, 2) practice verbalizing what you and your pair worked on by talking about it out loud to people, writing Pull Request and 3) practice communicating with project maintainers via GitHub issues/comments/PRs
### Open Source Projects to Lead:
1. Exercism (Front-end, Ruby, Go): https://github.com/exercism/exercism.io/issues
2. HoodieHQ (JavaScript on front and back): https://github.com/hoodiehq/camp/issues
3. Advanced: Gets even more meta: Debugging the Firefox DevTools debugger - mentored issues http://firefox-dev.tools/
4. More project ideas? Add some in the comments.
### Learners: New language/frameworks/coding learners
1. Make expectations clear as possible that this is not a language or framework oriented learning meetup. 
2. Refer new code learners to: Rails Learners (Jen D, Anna Mendoza), NodeSchool (http://nodeschool.io/los-angeles), LearnToCodeLA (Python, Functional, JS, all sorts of topics http://www.meetup.com/LearnToCodeLA/), GirlDevelopItLA (http://gdila.org/), WomenWhoCode LA (https://www.womenwhocode.com/la), MaptimeLA (JS for mapping meetup.com/maptimeLA)
3. Refer new language learners / new paradigm learners / framework learners to language/framework-specific meetups: Rust, GoLang, Functional, Swift/iOS, React, Angular, Rails, Ember, Django/Python.

**Comment by IanDCarroll** [comment]
One thing that we haven't done in past pairing is retros. We usually just devolve into general conversation and leave. 

I have very much enjoyed and found use in the current practice. If this is that, but more so, I'm all in. 

Also, I'd be interested in a list of legit meetups for the other stuff.

**Comment by machikoyasuda** [comment]
@IanDCarroll have you been to NodeSchool yet? that would be my #1 recommendation for JavaScript. i'm not as familiar with Python. but yes, we can definitely make a "list of meetups run by our friends" list.

**Comment by machikoyasuda** [comment]
@IanDCarroll what do you think of this? https://github.com/fullstackla/pairing-meetup/issues/25 #25

**Comment by malinatran** [comment]
As someone who has yet to contribute to open-source projects, would love to participate and learn from those with experience in doing this!
