### ISSUE TITLE
List of our favorite LA meetups

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#25]
Add your  #favorite/your LA meetup + link + description here 

Here I'm defining meetup as somewhere where you bring your laptop and actually code. Not talks.

Eventually we will publish this on GitHub / our site.

**Comment by machikoyasuda** [comment]
### JavaScript - West
- JavaScript / NodeSchool / Saturdays, monthly / Westside / http://nodeschool.io/los-angeles/ - front-end JS, back-end JS, lots of mentors, good space, lots of parking, pizza. Legit. 
- Learn to Code study group for JS: http://www.meetup.com/LearnToCodeLA/events/231581165/ in Culver City - casual coworking style
- Women Who Code one-off JS workshops: http://www.meetup.com/Women-Who-Code-LA/events/231574006/ 
- GDI Mar Vista study group: http://www.meetup.com/Girl-Develop-It-Los-Angeles/events/231261358/ 

### JavaScript - East
- LA Coders co-learning group / Weekends / KOREATOWN / https://www.facebook.com/groups/1678140759095725/
- The JavaScript Meetup / Glendale Panera http://www.meetup.com/thejsmeetup/

**Comment by machikoyasuda** [comment]
### Meetups hosted by dev shops:

### Slightly more advanced full-stack things
- LA Software Workshops: multilingual, full-stack application workshops / some beginner, some intermediate/advanced / Downtown LA, weeknights and weekends - run by 8th Light consultancy in downtown http://www.meetup.com/LA-Software-Workshops/ 

### General one-off - West
- Pivotal Labs: THE OG - Pair Exchange and Extreme Roundtable http://www.meetup.com/xp-los-angeles/
- Carbon 5: Wed. Night Hack Nights http://www.meetup.com/Hack-Night-at-Carbon-Five-LA/events/230577289/

**Comment by machikoyasuda** [comment]
### Ruby & Rails - East
- Learn to Code LA: Beginner Ruby South Pas Study Group http://www.meetup.com/LearnToCodeLA/events/231125799/
- Learn to Code LA: Monday Nights / Front End Project workshop nights at Tom n Toms in Little Tokyo
  http://www.meetup.com/LearnToCodeLA/events/231402097/
- LA Eastside Ruby: Problem Sets @ Panera Bakery in Glendale - longest running Ruby meetup in LA ever?! <3 http://www.meetup.com/LA-Eastside-Ruby-Rails-Study-Group/events/230709907/

### Ruby & Rails - Mid
- Code Night: Wednesdays, Larchmont, http://www.meetup.com/rubyinhollywood/

### Ruby & Rails - West
- LA Westside Ruby: http://www.meetup.com/Los-Angeles-Womens-Ruby-on-Rails-Group/events/pgwrslyvkbsb/

### Python - East
- Learn to Code LA: Python study group http://www.meetup.com/LearnToCodeLA/events/231263983/ 

### Web - Valley
- Web Study Group, Women Who Code: http://www.meetup.com/Women-Who-Code-LA/events/230114800/

### Web - West
- Web Study Group, Women Who Code / Python Office Hours with Pyladies at Crashspace (Culver City) http://www.meetup.com/Women-Who-Code-LA/events/230863565/ http://www.meetup.com/Pyladies-LA/

### Web - South Bay
- Code District, various free one-off workshops in Torrance: http://www.meetup.com/code-district/

### Web - Long Beach
- Python http://www.meetup.com/Long-Beach-Python/

### Functional - East
- Learn to Code LA: Functional Programming study group http://www.meetup.com/LearnToCodeLA/events/231403334/

**Comment by machikoyasuda** [comment]
### CSS
- http://www.meetup.com/CSS-LA/ @cssla

**Comment by IanDCarroll** [comment]
It's a seemingly comprehensive list. Thanks for going to the trouble to make it :) You've failed to miss anything I would have added.

**Comment by machikoyasuda** [comment]
### One-off events:
- Rails Girls LA
- Django Girls 
- Linux Chix http://linuxchixla.org/

**Comment by leighphan** [comment]
### **General - Long Beach**
- Code & Coffee: Casual hack morning; open office space; helpful, welcoming folks!
  http://www.codeandcoffeelb.org/
  http://www.meetup.com/lbtech/events/221553831/

**Comment by karimamer** [comment]
http://www.fplongbeach.com/

**Comment by karimamer** [comment]
code and coffee changed their meetup page http://www.meetup.com/code-and-coffee-Long-beach/
