### ISSUE TITLE
Come up with list of non-coding issues

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#28]
List of issues that don't involve coding:
- Documentation
- Design

**Comment by jendiamond** [comment]
Credit for pairing

**Comment by machikoyasuda** [comment]
@jendiamond that is here: https://github.com/fullstackla/pairing-meetup/issues/26 :D 

I meant more like "Come up with a list of issues that non-coders can do, like design and documentation"

**Comment by machikoyasuda** [comment]
@leighphan testing

**Comment by IanDCarroll** [comment]
just brainstorming:

posts of pics and recap of the group's and the project's progress on social media or a super-special blog. Basically: media/marketing.

Also organization. Someone who can organize the project's issues's and assign appropriate work so more people can be on-boarded quickly. That'd probably be the owners' realm, tho.
