### ISSUE TITLE
10 min. lightning talk, up for grabs: Using binding.pry for Ruby debugging

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#32]

**Comment by kennethlee** [comment]
I'd be interesting in hearing this one.

**Comment by machikoyasuda** [comment]
@kennethlee have you used pry before?? just curious. it will help me make a better talk. how else do you debug ruby/rails stuff otherwise?

**Comment by kennethlee** [comment]
@machikoyasuda I honestly don't remember much about it; my past exposure to it is limited to the few times I've played around with it.

**Comment by jaimemendozadev** [comment]
I'd also be interested in hearing this talk.
