### ISSUE TITLE
Tuesday, June 28th: Potential Issues to work on

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#34]
1. Code: Keep working on the last PR from last week https://github.com/exercism/exercism.io/pull/2954
2. Specs: Write specs for that PR
3. Learn a new tool: Have people test out binding.pry, debugger.
4. Continue to use a not-new tool: Use GitHub issues instead of Mopad.
### How to use GitHub at the Pairing Meetup:
- If you get a really bad installation bug, make an Issue. Describe the bug.
- If you figure something out really cool, add it to the Wiki or add it to our README. Use a PR.

**Comment by machikoyasuda** [comment]
https://github.com/jdorfman/awesome-help-wanted @jdorfman

**Comment by machikoyasuda** [comment]
If you need to be added to exercism team, comment here with your Github name!

**Comment by machikoyasuda** [comment]
`lenkli67:team-pagination` https://github.com/exercism/exercism.io/pull/2954

**Comment by machikoyasuda** [comment]
### Checking out an unmerged remote pull request

Follow these instructions: https://help.github.com/articles/checking-out-pull-requests-locally/
- Make sure `upstream` is set to be `https://github.com/exercism/exercism.io.git (fetch)`
- Check by running `git remote -v`
1. `git fetch upstream pull/2954/head:team-pagination`
2. `git checkout team-pagination`

thanks @jendiamond @thomasjinlo @lenkli67

**Comment by jendiamond** [comment]
@machikoyasuda 
@jendiamond
- Chad
- jeff
- ed
- anna
- michael
- andre
- hashim lisa
- ranit
- ian
- kenny
- eddy
- emeril
- david
- Jim
- natalie
- thomas 
- lena

**Comment by kennethlee** [comment]
@kennethlee
@jim6652

**Comment by MrExeter** [comment]
@MrExeter

**Comment by ghost** [comment]
@edvernon

**Comment by hash167** [comment]
@hash167

**Comment by davidtansf** [comment]
@davidtansf

**Comment by server-monitor** [comment]
michael => @server-monitor

**Comment by machikoyasuda** [comment]
Fix: Fixes test_managing_a_team_as_sole_manager failing spec
- Adds params['page'] or 1, in case params['page'] is nil, in the case of a brand new team without any problems.
- Open Source Pair Programming in LA: Paired
  at IndieDesk with @jendiamond, @lenkli67, @
  kennethlee, @jim6652, @mrexeter, @edvernon,
  @hash167, @davidtansf, @server-monitor

**Comment by IanDCarroll** [comment]
```
@_IanDCarroll_
```
