### ISSUE TITLE
Parking strategies

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#37]
We have $10 validation for the area.

Cheaper parking options in the area? Share.

**Comment by machikoyasuda** [comment]
- Adventurous free parking spot: https://www.google.com/maps/place/LAUSD/@34.0562413,-118.2595508,17z/data=!3m1!4b1!4m5!3m4!1s0x80c2c7adc8a5ea1d:0x97faa50d6dddccfd!8m2!3d34.0562369!4d-118.2573621
- Take this walk: https://www.dropbox.com/s/jren8e6pln3skun/Screenshot%202016-06-28%2019.10.11.png?dl=0

**Comment by machikoyasuda** [comment]
- 300 S Grand Ave, $11

**Comment by IanDCarroll** [comment]
For the adventurous, there is a solution that transfers monetyary cost to calorie cost, wear on your feet and possible problems being eaten by alligators and/or falling into Narnia. Also it's an adventure not recommended for late nights by yourself. But it's a magical journey.

 Thanks to Machiko for suggesting it, but find me for secret parking knowledge ;)

**Comment by jaimemendozadev** [comment]
Small parking lot located at 200 S Olive St, Los Angeles, CA 90012 (corner of 2nd and Olive St.). 

Parking is roughly $6 after 4 p.m.

*Caveats:
1) It's a VERY small parking lot on a hill. 
2) You can only enter by making a right on Hill St. and entering the lot through there.
