### ISSUE TITLE
Needs help installing Ruby/RVM/Rails/Postgres

### ISSUE THREAD

**Issue by IanDCarroll** [fullstackla/pairing-meetup#38]
What are some low-skill contributions noobs(like me) can make?
These are the "Shovel the latrine" or "De-gum the cafe tables" tasks.
they should be:
1. Low-skill so the barrier to contribute is lowered.
2. Highly annoying/tedious that the level-20 Coders shouldn't waste time on.
3. Highly useful/necessary so it's a real contribution.

For those who are fearlessly willing to don their rubber gloves, get down on their hands and knees, and f**king work!

**Comment by machikoyasuda** [comment]
@IanDCarroll have you been able to get Exercism.io running locally on your computer?

**Comment by IanDCarroll** [comment]
forked the repo, if that's what you mean. I think I have the environment set up with relating to this repo, my own and exercism's in the kosher configuration.

**Comment by machikoyasuda** [comment]
Were you able to run the bin/setup and the foreman command and open localhost:4567 on Chrome and log in?

On Wed, Jun 29, 2016 at 6:52 PM -0700, "Ian Carroll" notifications@github.com wrote:

forked the repo, if that's what you mean. I think I have the environment set up with relating to this repo, my own and exercism's in the kosher configuration.

**Comment by IanDCarroll** [comment]
I am having trouble understanding how to run the bin/setup. With what do I run it? I tried RVM, but either that's not right, or I need to configure RVM first.

**Comment by machikoyasuda** [comment]
You make sure you are in the directory for exercism and then you type "bin/setup" and then you press enter on your keyboard

On Fri, Jul 1, 2016 at 1:25 PM -0700, "Ian Carroll" notifications@github.com wrote:

I am having trouble understanding how to run the bin/setup. With what do I run it? I tried RVM, but either that's not right, or I need to configure RVM first.

**Comment by machikoyasuda** [comment]
type bin/setup. no quotation marks. 

On Fri, Jul 1, 2016 at 2:26 PM -0700, "Machiko Yasuda" machikoyasuda@gmail.com wrote:

You make sure you are in the directory for exercism and then you type "bin/setup" and then you press enter on your keyboard

On Fri, Jul 1, 2016 at 1:25 PM -0700, "Ian Carroll" notifications@github.com wrote:

I am having trouble understanding how to run the bin/setup. With what do I run it? I tried RVM, but either that's not right, or I need to configure RVM first.

**Comment by machikoyasuda** [comment]
Type bin/setup into Terminal (or whatever you use) and click Enter on the keyboard and make sure you are in the exercism repository with the code that turns exercism (not the directories with all your exercism problem codes).

**Comment by IanDCarroll** [comment]
I've had some problems with RVM, but I think I've mostly gotten through them. The current problems have something to do with postgreSQL, I think. I tried creating a template1 DB with my name as a user, but now when I run `bin/setup` I get

```
The Gemfile's dependencies are satisfied
Password: 
Password: 
ERROR:  must be superuser to create superusers
Password: 
createdb: database creation failed: ERROR:  role "exercism" does not exist
rake aborted!
Failed to create database
...
```

If i try `sudo bin/setup` I get:

```
Your Ruby version is 1.9.3, but your Gemfile specified 2.2.2
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Your Ruby version is 1.9.3, but your Gemfile specified 2.2.2
```

running `rvm list rubies` i get

```
rvm rubies

=> ruby-2.2.2 [ x86_64 ]
 * ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

running `ruby -v` I get `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]`
So I don't know what it's talking about. anyway, Sudo might be wrong to begin with.
I'm thinking I need to do something in postgreSQL, but maybe someone else has encountered this trouble or can see what step I'm missing.

**Comment by machikoyasuda** [comment]
I am retitling this issue to your installation bug/needs help. We can solicit other members to help you in person or via this issue. 

There are definitely other ppl in this meetup that have gotten that `sudo bin/setup` bug you ran into.

**Comment by IanDCarroll** [comment]
That's super helpful! This seems to be a few bugs/inexeperience tangled together, so even getting a few bits unwound would be killer! :neckbeard:

**Comment by machikoyasuda** [comment]
Resolved: https://github.com/exercism/exercism.io/issues/2969 

Lesson learned: Knowing what directory you are in and being in the one configured with exercism matters. @IanDCarroll
