### ISSUE TITLE
What to do if people can't get Exercism installed?

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#4]
Alternatives:
- Three-person pair
- Work on someone else's machine
- http://nodeschool.io - Command Line installation, has a very good beginner JavaScript tutorial
- Learn Command Line / Ruby / Python the Hard Way
- Codecademy, Khan Academy

**Comment by alexandru-calinoiu** [comment]
Not an answer to your question but more a prevention

Compile a list of common causes this might happen and come up with answers, this can be a good section for the wiki.

**Comment by machikoyasuda** [comment]
@learningnerd wrote a great Windows installation guide: http://learningnerd.github.io/2015/05/06/exercism/
