### ISSUE TITLE
Tuesday, July 12th 2016 - Scratch Pad + Summary 

### ISSUE THREAD

**Issue by jendiamond** [fullstackla/pairing-meetup#49]
7-12-2016

@jendiamond
@MrExeter
@curvgrl5000
@lisamarie616
@postem1
@iandcarroll
@kennethlee
@havenwood
@stephaniewilkinson
@edvernon

$ bundle !!

pry-rescue

bundle exec rake test TEST=test/acceptamce/team_test.rb

== $0  - last selected dom element

page.all("a").map(&:text)

ls page
page.body
page.current_url

rake routes
visit('/teams/slate/
authorization header

Iser .pluck DICTINCT

Team.find_by(
ls  Team

Conrad Irwin repl driven development
https://www.youtube.com/watch?v=D9j_Mf91M0I

Final:
team does not have any members

**Comment by server-monitor** [comment]
> bundle exec rake test TEST=test/acceptamce/team_test.rb

Small typo. "acceptamce" instead of "acceptance". This won't run unless the folder is actually called "acceptamce".

**Comment by jendiamond** [comment]
Great catch @server-monitor

**Comment by server-monitor** [comment]
@jendiamond That's what I do. I monitor... hehehe

**Comment by jendiamond** [comment]
@edvernon

Post test and name to add to current pull.  What is the location of test.

How to login to local running exercism?  Otherwise you are not allowed access to "next page".

Command to run test.

Is the test being run on a page that is being served live?  Or offline?
