### ISSUE TITLE
I need to be added to the DTLA Pair Programming team!

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#5]
Comment with your GitHub handle here.

**Comment by machikoyasuda** [comment]
@mijoru

**Comment by ghost** [comment]
easyspirit

**Comment by machikoyasuda** [comment]
@easyspirit I invited you! You should get an e-mail invitation shortly from Exercism.io, to the e-mail address associated with your GitHub account.
