### ISSUE TITLE
design choices for local-meetup page CSS

### ISSUE THREAD

**Issue by IanDCarroll** [fullstackla/pairing-meetup#50]
Before I try to tackle CSS, I'd like to ask for a discussion and general consensus on how the page should look.
1. what color scheme?
2. Layout?
3. Nav bar or other peripherals?
4. Logo/picture?
5. anything else I've missed in this quick list.

If I do it on my own, It'll be the webage equivalent of showing up at the school spring semi-formal dance in a Viking helmet and a cape. So input is very much needed! :hankey: :bowtie: :hankey:

**Comment by machikoyasuda** [comment]
the most important thing i would say is that it is legible and mobile-friendly. everything else is secondary.

**Comment by IanDCarroll** [comment]
Excellent points. Legible shouldn't be too much of a problem. Mobile-friendly... might have to look into that.

But still I need an aesthetic direction to go in. I guess I could go off of that basic principle to inform most of my choices, but I still need to make specific choices. If no one has any suggestions for colors, I'll just have to make something up on my own. I didn't want to speak for the group that way without at least consulting people.

**Comment by machikoyasuda** [comment]
@IanDCarroll 

good places to start/procrasti-work on aesthetics:

https://www.google.com/fonts#!

find a red/green color blind-friendly combo: http://colorbrewer2.org/

**Comment by IanDCarroll** [comment]
I'm aware of the danger :smile: 
:question: "procrasti-work" => related to "yakshaving"

This is my theatre background kicking in. I'm looking for **direction**. And just as you do on stage, design of any kind requires concrete consious well-considered **specific choices**.

But I guess I can just come to those on my own :smiling_imp: 

I'll still be happy to take notes and make adjustments afterward tho :angel:

**Comment by machikoyasuda** [comment]
can we make this more like Improv where you just do / say whatever works best on 2 seconds notice?

**Comment by IanDCarroll** [comment]
Ok, I can roll with that. :smile:
