### ISSUE TITLE
Meetup Not in Downtown LA

### ISSUE THREAD

**Issue by neoadventist** [fullstackla/pairing-meetup#52]
The Github Repo says that the meetup is is Downtown LA. This is Incorrect.

**Comment by kpearson** [comment]
Can you provide a use case. :zap:

**Comment by neoadventist** [comment]
Can you be more specific? @kpearson

**Comment by server-monitor** [comment]
There's a meetup on Tuesdays at IndieDesk in DTLA. The one scheduled for today is located at MaxCDN.

http://www.meetup.com/la-fullstack/events/232548531/

**Comment by kpearson** [comment]
Fixed 👟
