### ISSUE TITLE
Noobie Outreach

### ISSUE THREAD

**Issue by IanDCarroll** [fullstackla/pairing-meetup#54]
Maybe I'm thinking too far ahead here, but I think we ought to brainstorm some ways we might encourage the timid and new to learn about how awesome it is to work on projects with others and contribute to open source.

There's word-of-mouth, but I was wondering if there is anything else we can do to reach a target audience (If we're even ready for that).

**Comment by machikoyasuda** [comment]
Do you think you would learn faster and better if there were more serious beginners like you? Do you want more serious beginners to pair with?
Our main issue is that we have to keep the newbie/experienced ratio balanced. We want experienced people who want to pair with even more experienced people to be able to do so. 
Also small group is easier to handle. My personal approach to outreach is: "if theyre serious enough they will come and/or contact us". I know you cant see it but we have 5 or so people ranging frim beginners joining the group every week. they just dont show up always. 

On Thu, Jul 14, 2016 at 12:14 AM -0700, "Ian Carroll" notifications@github.com wrote:

Maybe I'm thinking too far ahead here, but I think we ought to brainstorm some ways we might encourage the timid and new to learn about how awesome it is to work on projects with others and contribute to open source.

There's word-of-mouth, but I was wondering if there is anything else we can do to reach a target audience (If we're even ready for that).

**Comment by machikoyasuda** [comment]
closing this for now :)

**Comment by IanDCarroll** [comment]
I suppose I don't know the balance we want to maintain.
Also, I guess this is more about a desire to get myself strong enough to start helping newer people.
Teaching is a useful way to learn it yourself.
Also this is because I'm feeling very good about what we're doing, and want to build things more. :smile:

**Comment by machikoyasuda** [comment]
we want everyone to be learning and challenged more. so we don't want it to be 99% newbies. then the mentors will spend more time navigating vs. driving/coding.

i have faith that serious beginners will find the meetup and join and come when they're ready.
