### ISSUE TITLE
Wed. July 27 - Notes

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#59]
### Stand Up
- @MachikoYasuda - looking for pair - https://github.com/fullstackla/hoodie-map-chat-demo + https://github.com/hoodiehq/camp/issues/14
- @IanDCarroll is working on https://github.com/fullstackla/pairing-meetup/issues/55 - do you want a pair?
- maybe @jaimemendozadev on reaction
  @jendiamond is working on https://github.com/exercism/exercism.io/pull/2981
### Announcements
- LA tech world: MaxCDN acquired
- LA open source world: MaptimeLA & OSM @ State of the Map
- A local LA open source company: Reaction Commerce
- Outreachy applications: https://www.gnome.org/outreachy/
##### Looking for a project? Ideas
- First timers: This is all for you: https://github.com/fullstackla/pairing-meetup/wiki/Your-first-project-ever%3F-Welcome!-Start-here. 
- More for first-timers only: https://twitter.com/first_tmrs_only
- Our curated list here: https://github.com/fullstackla/pairing-meetup/issues/57
- @jdorfman's Awesome Help Wanted https://github.com/jdorfman/awesome-help-wanted
- https://www.codemontage.com/ 
- https://www.codetriage.com/ 
- https://openhatch.org/
- Meteor/Mongo/Node http://blog.reactioncommerce.com/how-to-get-involved-with-reaction-commerce/ https://docs.reactioncommerce.com/reaction-docs/development/installation

**Comment by jdorfman** [comment]
Can't wait. See you all Wednesday.

**Comment by machikoyasuda** [comment]
@jendiamond hi

**Comment by IanDCarroll** [comment]
I'm sure I'm not alone in exploring something with meteor

**Comment by dj-m** [comment]
@machikoyasuda I'd vote for Homebrew as a project going forward

**Comment by machikoyasuda** [comment]
https://tracker.hood.ie/

**Comment by machikoyasuda** [comment]
`nvm install v4.4.7`
`node -v`
(verify that you have v4.4.7)
`npm install --global npm`
`npm -v`
(verify that you have 3.10.5)
`npm install`
`npm start`

## if you have the old hoodie already, you may have to run these as well

(if you have hoodie already)
`npm uninstall --global hoodie`
(take a breath in between rm -rf)
`rm -rf node_modules`
`npm install`

## npm install hoodie

npm install --save hoodie
(--save adds to package.json)
npm start (runs start script defined in package.json)

@dj-m @davidtansf

**Comment by jdorfman** [comment]
### Changelog
- [Awesome JSON Datasets: Fixed Encoding issue](https://github.com/jdorfman/awesome-json-datasets/commit/be9391924065aec81bf7812c6bb434f6348ed887)
- [Awesome Help Wanted: Added Documentation Section](https://github.com/jdorfman/awesome-help-wanted/pull/12)
- [Awesome Help Wanted: Added more repos to Documention](https://github.com/jdorfman/awesome-help-wanted/pull/13)

**Comment by jaimemendozadev** [comment]
Submitted a request to change the documentation:
https://github.com/jaimemendozadev/documentation/commit/e43981d7b437989655063d184fae2e73a652404f

*My small contribution for the night. 😄
