### ISSUE TITLE
Tonight's Talk: Homebrew Summer of Code

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#62]
http://eirinikos.github.io/2016/06/02/summer-begins/

**Comment by machikoyasuda** [comment]
Maybe a short talk :)

**Comment by machikoyasuda** [comment]
@eirinikos can we organize here ? :)

**Comment by eirinikos** [comment]
Sounds good! We're thinking about late August or sometime in September? Happy to talk about [Outreachy](https://www.gnome.org/outreachy/) in general, too. 😄

**Comment by machikoyasuda** [comment]
@eirinikos How about the Aug. 24 Wed. meetup date? Could that be a good speaker date? We can post a Q and A before that. I want people to learn about it before the Outreachy deadline.

**Comment by eirinikos** [comment]
Cool! 👍

**Comment by machikoyasuda** [comment]
@kpearson https://docs.google.com/presentation/d/1qRJ83rrb_flP7odoAnBjJxyQETYdsauN3K4hy-Qg9ns/edit#slide=id.g165628c9cc_0_42 here are the links for tonight's talk with @eirinikos

**Comment by kpearson** [comment]
Awesome. Just awesome.

Is she okay with us recording it and putting it on youtube?

— Kit

**Comment by machikoyasuda** [comment]
@eirinikos 🆙  ☝️

**Comment by eirinikos** [comment]
👍  Record & post away!
