### ISSUE TITLE
Possible Talk: Mapillary / Leaflet / mapping libraries

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#65]

**Comment by server-monitor** [comment]
I don't know what this is.

**Comment by machikoyasuda** [comment]
@server-monitor We are going to get people to talk about these different JavaScript open source mapping tool libraries:

http://leafletjs.com/
https://github.com/mapillary/mapillary-js

First we will have people use the libraries to get familiar with it

Then we will invite devs to speak about it

And lastly we can work on issues to add new features/fix bugs for this open source project :)

**Comment by kennethlee** [comment]
I'd be interested in a talk on/project using leaflet

**Comment by machikoyasuda** [comment]
@kennethlee you're in luck, we're working on one now using Leaflet/Hoodie: https://github.com/fullstackla/pairing-meetup/issues/56 https://github.com/hoodiehq/hoodie-app-mapchat/pull/14

We are also in the middle of updating the README on that repo cos it is not out of date.

**Comment by machikoyasuda** [comment]
@kennethlee instructions i wrote up so far are here: https://github.com/fullstackla/pairing-meetup/issues/59#issuecomment-235786101

**Comment by server-monitor** [comment]
@machikoyasuda Thank you for the enlightenment. How does Google maps relate to these tools? It's what I've been using in my personal projects. It would be interesting to learn other mapping tools though.

**Comment by machikoyasuda** [comment]
@server-monitor the Google Maps API costs money after a certain point. Leaflet is a free open source alternative, which means: 1) you dont have to pay money to use it, 2) we can contribute to it, 3) they use OpenStreetMap data instead of private Google data

**Comment by server-monitor** [comment]
@machikoyasuda I tried it and it works! 

https://mapmymeetups.herokuapp.com/meetup_events/leaflet

This awesome. There's no need for no stinkin' account setup and API key. I've been playing with maps lately. Google is OK I guess. They have a cap at 25k for the free account. Does leaflet/OSM have limits? I can't seem to find it anywhere in their docs.

**Comment by machikoyasuda** [comment]
Woohoo!
I do not think Leaflet does... but the mal tiles might. For example, Stamen and MapBox provide custom map tiles hosted for a fee. You can ask the developers this through GitHub. And if they should add this answer to their website, you can suggest they add it with a PR :) 

On Fri, Jul 29, 2016 at 10:10 PM -0700, "Server Monitor" notifications@github.com wrote:

@machikoyasuda I tried it and it works! 

https://mapmymeetups.herokuapp.com/meetup_events/leaflet

This awesome. There's no need for no stinkin' account setup and API key. I've been playing with maps lately. Google is OK I guess. They have a cap at 25k for the free account. Does leaflet/OSM have limits? I can't seem to find it anywhere in their docs.

**Comment by machikoyasuda** [comment]
@IanDCarroll check out @server-monitor's map! maybe you two can pair on adding your meetup data points onto this map programmatically. https://mapmymeetups.herokuapp.com/meetup_events/leaflet

**Comment by server-monitor** [comment]
@machikoyasuda It already has that functionality. You can enter a meet up group or event link (with the scheme (HTTP or HTTPS), press "Submit" and it will put a marker on the map of the venue location. You can also enter in a keyword and it will map all the related meet up events.
