### ISSUE TITLE
fullstack 🎃  Hacktoberfest edition, ft. CodeLabOC & Boba.js

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#66]
# Issue planning:

https://github.com/fullstackla/pairing-meetup/blob/master/hacktober_2016.md
# Remaining to dos:
- Make meetup.com invites
- Initiate carpooling/transportation conversations
- Keep adding issues to pair on

**Comment by machikoyasuda** [comment]
@leighphan this will be here for when you need it :)

**Comment by machikoyasuda** [comment]
@leighphan GitHub issues are a way for open source groups to organize their to-do lists for the project. We use this list to keep track of ideas we have for the meetup, assign tasks to members and to discuss the issues. I made this Issue to remind myself that one day we will want to do an open source pairing meetup in Fullerton.

**Comment by leighphan** [comment]
@machikoyasuda Thanks for opening this up! Would be awesome to do a collab meetup :)

**Comment by machikoyasuda** [comment]
@leighphan @gr2m do we have a preference for an October date/location of boba.js slash hacktober slash la-&-oc code hack fun day? weekend probably, right?

**Comment by gr2m** [comment]
yeah let’s do a weekend!

I’d say we either try to organize a place a bit outside of LA were we can stay Friday - Sunday, that’d be super cool, if you have any idea where we could do it? I’d say 10-15 people would be a good group.

Alternatively and probably easier to organize and attend would be a place that is cental / easy to get to in LA, where we could be full day Saturday & Sunday, just meet in the morning, leave in the evening.

What do you think?

**Comment by machikoyasuda** [comment]
maybe public-transit-oriented like near a Metrolink Station -- @leighphan is codelab's coworking space near metrolink?

**Comment by kangashley** [comment]
3 blocks away, according to [this](http://www.metrolinktrains.com/stations/detail/station_id/97.html)! (Pro Desk Space is on Amerige, between Harbor and Pomona.)

**Comment by gr2m** [comment]
here is Pro Desk Space’s website http://www.prodeskspace.com/

**Comment by leighphan** [comment]
Weekend sounds good -- although Sundays Pro Desk Space is usually occupied. I'm checking availability with our office manager and will report back.

Our space is walking-distance from the Fullerton Metrolink, which runs directly to Union Station!

**Comment by leighphan** [comment]
Best weekends would be Oct 8, 15, 29th. Does anyone have a preference on any of those?

We have a conference room where we host CodeLab that would be able to fit up to 16 people. The rest of the space is usually used during weekends (although if it's pretty empty maybe we can spread out :)).

**Comment by machikoyasuda** [comment]
What about Sunday the 16th? (I'll be in OC but busy on the 15th @leighphan cos Katy Bowman will be doing her book signing :P)

**Comment by gr2m** [comment]
Sunday 16th sounds great to me :)

**Comment by leighphan** [comment]
(@machikoyasuda was wondering when that event was 😆 )

That date should be good for Pro Desk Space; gonna confirm with the CodeLab crew. :)

**Comment by gr2m** [comment]
okay, let’s figure out how to make Boba at the event :) Also I scored bobajs.org because buying domains makes me happy

**Comment by machikoyasuda** [comment]
Brainstorming event description/general schedule: @kpearson 

Hi there,

Any of those dates work for me. I’m happy to help as needed. Just send me specific tasks.

I’m happy to create an event page on the FullstackLA site and MeetUp.com.

## Date/Time:

Sunday October 16

## Location:

Pro Desk Space

## How to get here:
1. LA group can take the Metrolink together
2. Public Transit & Parking information (though Parking in OC should be free and plentiful right? :) ), 
3. Carpooling organizing info

## What will go on:
- I'm thining we could:
- Pair on personal public projects
- Show & Tell after - what you worked on
- These can be code projects or editorial projects or art projects or map / data visualization projects or anything. Anything that uses open source code (which is like, almost everything!)?!

## Important questions: Food & Snack related -
- @leighphan Is there Boba within walking distance of Pro Desk Space? If not, where can we go?
- Is there a cool local hole in the wall awesome local legit non-cash-only lunch place we can all walk / go to nearby? 

Maybe the goal of boba.js could be to highlight cool rad independent food/snack/beverage places nearby to the venue.

**Comment by leighphan** [comment]
All sounds good to me. And yes, we have plentiful parking; I can send out the map we use for our meetup to show parking locations. :)

Downtown Fullerton is dessert/snack/food central! We've got at least 3 spots that have boba - all walking-distance. I'm noticing more frozen yogurt places nearby (even _organic_ frozen yogurt).

Will scout some indie food spots - we've got plenty of those. :)

**Comment by gr2m** [comment]
sounds great :)

**Comment by leighphan** [comment]
Some of us at CodeLab have a preference for Oct. 8th - would that work for everyone?

**Comment by gr2m** [comment]
I can’t do 8th unfortunately, I’ll be out of town that weekend

**Comment by leighphan** [comment]
Weekend of 22nd?

**Comment by gr2m** [comment]
works for me :)

**Comment by machikoyasuda** [comment]
that is the weekend of Rails Girls LA and 8th Light's SCNA Conference at USC! 

On Fri, Sep 23, 2016 at 9:54 PM -0700, "Gregor Martynus" notifications@github.com wrote:

works for me :)

**Comment by leighphan** [comment]
@machikoyasuda and GDI Website Weekend! ‼️

Alright, let's make it Oct. 16. :)

**Comment by kpearson** [comment]
October 16th works for me.
How long is the event? (Start time? End time?)

I need a little help with a discription. I'm trying to get a grasp on the main objective of the event.
I think it would help to decide on a headline or two.
What is the main idea we are organizing around?
Some ideas pulled from above:
- open source
- pair programming
- coding
- helping first-time coders
- hacktoberfest

All of these things can be part of the event, what I'm after, is the primary thing people will be thinking about when the walk in the door.
Having a clear main idea and a couple supporting goals will help a lot I think.

Ideas:
- Enjoy open source with friends.
- Learn the ABC of open source.
- It's Hacktoberfest season!
- Let's open source all the things.

**Comment by machikoyasuda** [comment]
## Purpose:
- Why weekend and why OC? - To have a weekend event in a new neighborhood: (1) To introduce people to a new neighborhood + local food/boba places, (2) To get people who can't regularly make a weeknight in LA to come., (3) To introduce people from different neighborhoods (LA, OC) to each other. To outreach out farther away from LA. 

## Goals:
- What will we be doing and why? It's Hacktober - Time to Pair & Share: To pair on projects we usually might not prioritize, like open source projects, personal public passion projects, documentation, editorial projects, and share those with other people. It doesn't have to be coding. It can be design, coding, writing, editing, dev ops, web security, anything that involves working on open source libraries.

**Comment by gr2m** [comment]
Maybe we can model it a bit after https://github.com/welcome-to-open-source/Atlanta? It’s pretty straight forward, 3 things come together:
1. People new to Open Source come to become open source contribute or to contribute to new projects.
2. Experienced folks help coach beginners with setups, questions, debugging, etc
3. Open Source projects (which includes your personal side project :) ) prepare beginner-friendly, well documented issues and remote support via slack or GitHub during the time of the event, and try to get pull requests reviewed & merged fast 

The goal is that by the end of the day everyone should have contributed at least one thing to an Open Source project, and ideally get to know a community that they feel comfortable with contributing to in future.

**Comment by IanDCarroll** [comment]
I probably can't come thanks to work obligations, but I wanted to share an idea I've heard about on how to format the lightning talks to make them super spontaneous and agile:
1. Get a bunch of post-its (or index cards w/ tape) and some sharpies.
2. Have everyone take a card (or two) and write down a show-and-tell, discussion question or a talk topic.
3. Post them all on a wall.
4. Everyone gets 3 votes to dot the cards they're most interested in. They can put (1 dot on three different cards), (2 dots on one card and 1 on another), or (all 3 dots on one card.)  **!! You _can_ vote for yourself. !!**
5. The cards with the most dots speak first, 5 minutes each until you're out of time for talks. The group can up-vote a topic to give it 3 more minutes.

@machikoyasuda when you compile your list like the ones open source Atlanta does, it might be pretty slick to have each of them written up on an index card or post-it and on the wall so that people can inspect them as they socialize and think about what they'd like to pair on and with whom. The tangible part of pulling the note off the wall to claim it, then putting it back up on a submitted pull-request column can be satisfying. Everyone gets to see what the group did by the end of the mini-conference!

**Comment by dotproto** [comment]
> okay, let’s figure out how to make Boba at the event :) Also I scored bobajs.org because buying domains makes me happy

I just grabbed boba.team for the same reason! 😅

I also snagged the GitHub org @boba-js and will probably grab other social media accounts, though I'm terrible at the social.

**Comment by machikoyasuda** [comment]
i moved the list of issues to here: https://github.com/fullstackla/pairing-meetup/blob/master/hacktober_2016.md 

add issues/projects you want to work on during Hacktober day in OC there :)
