### ISSUE TITLE
Wed. July 27 - Reviews

### ISSUE THREAD

**Issue by IanDCarroll** [fullstackla/pairing-meetup#68]
Just got my CSM certificate, so that's immediately given me a new perspective. Hope I'm not rocking to boat in an unpleasant fashion here, please post questions about this process and anything that might be causing this to not be helpful! :neckbeard:  

I noted a long time ago that we don't take any time to transparently inspect our progress, so I wanted to set up some rituals to allow that. The Review is one of the rituals from scrum. The Daily Scrum we already do at the meetup is one of them. The other 3 are Backlog Grooming, Planning, and Retrospective.

Here, I'd like to set up an issue around the review.
**What do I mean by review?**
A Review is our time to show off the new work we've done. In a kosher Scrum environment, only work that meets our current "definition of done" gets into the review. I think that for our purposes, learning achieved might also meet that definition. we might want to make a simple formalization of what done is, but for now, the work can be called done if you personally think "It's done."

The other half of the end-of-meetup process is the Retrospective, which will be in issue #69 .

The question to answer:
**What did we get done? That is, what value did we deliver in the last Meetup to ourselves and to the Open Source Community?**

**Comment by IanDCarroll** [comment]
I'll kick this off:
7/26/16
I learned to feel more comfortable with error messages and posting issues on GH when I got stuck. This has been productive for me because I have a better understanding of what kind of mindset is useful when encountering errors, and what actions are open for me to take in resolving them. I delivered a slightly more involved and better contributor to open source.

Here are the issues I've raised:
https://github.com/mapbox/geo-googledocs/issues/40 - Geocoding from the Google Sheet was stuck on a load screen.
https://github.com/reactioncommerce/reaction-docs/issues/63#issuecomment-235803314 Trouble installing reaction commerce locally

**Comment by machikoyasuda** [comment]
@IanDCarroll did you work with anyone or talk out loud with anyone or ask questions out loud with anyone on anything that helped you learn these things? what are you learning from the comments coming in from the issues you've posted? how did you learn things that you could not have learned necessarily if you were working solely by yourself?

**Comment by IanDCarroll** [comment]
@machikoyasuda what helped was being in the room with other developers and observing their unspoken attitudes while working. It might be a topic for the retro, but I probably could have learned more if I was more outspoken. I didn't want to harsh anyone's groove with questions.

getting comfortable with posting GH issues when I couldn't resolve it myself, and learning when was a good time to do that was something I probably did when you suggested it. I still have a lot of hesitation around error messages, but it was useful seeing others not hesitating when they encountered them, or as they set up hoodie on their local environments.
