### ISSUE TITLE
List of 450+ free online courses

### ISSUE THREAD

**Issue by server-monitor** [fullstackla/pairing-meetup#70]
As I was wasting time I on reddit, I came across this posting of a list of free online courses:

https://www.reddit.com/r/learnprogramming/comments/4vyhca/heres_a_list_of_450_free_online_programmingcs/

Same list in a github repo: https://github.com/jaalsh/free-programming-and-cs-courses

There's a variety of courses for different levels of proficiency, languages, etc. Only 3 Rails/Ruby courses though. I was surprised JavaScript only has 9. 

Anyhoo, I hope this helps.

**Comment by machikoyasuda** [comment]
This is very useful @server-monitor :) But we're gonna keep using GitHub issues for issues about making apps on GitHub/writing code. All other things can go in our Wiki or somewhere else for now. I'm closing this for now :) See you soon.
