### ISSUE TITLE
Wed. Aug. 10 ⚡ 📻  Show Notes

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#71]
Let's try something new. @kpearson and I want to maximize coding & pairing time, so we want to try putting our usual shpiel up in various places people can read ahead of time online or in person (like on PowerPoint, paper, something like that).

I'll start with kudos & announcements:
### kudos -

⭐ @jaimemendozadev - first PR on @hoodiehq merged: https://github.com/hoodiehq/documentation/pull/225
⭐ @kpearson :) 
### announcements -

⭐ 8th light's meetup is coming up: https://www.meetup.com/LA-Software-Workshops/events/232713877/ they have a shiny new office in Downtown LA, Metro-accessible.
⭐  we started tweeting. follow us for golden tips and all things socal open sourcing. twitter.com/fullstackla
### on the deck -

⭐ in Aug/Sep, we will have a local open source developer, Andrea, speak about coding on Homebrew, a Command Line interface app, that y'all have probably used, thru the Outreachy fellowship. the Outreachy fellowship's next deadline is https://www.gnome.org/outreachy/ Aug 22. it would be a great first gig for people in our meetup. 
### standup, qotd

⭐  thing to read of the week, http://hood.ie/blog/rgsoc-team-rookies-month-1.html

anyone else have any kudos or announcements? add em here:

**Comment by machikoyasuda** [comment]
- devspace: tool for keeping up with github tool, zeno rocha

**Comment by machikoyasuda** [comment]
- http://www.lasoftwarecraftsmanship.com/

**Comment by jdorfman** [comment]
**Links:**
- https://github.com/git-tips/tips
- https://app.devspace.io/
- https://github.com/FallibleInc/security-guide-for-developers

**Comment by machikoyasuda** [comment]
who's here:
@kpearson 
@cacheflow
@machikoyasuda
@jaimemendozadev
@marina-miranovich
@gr2m
@thomasjinlo
@kennethlee 
@IanDCarroll 
@caseytherocket
@patriciarealini
@thebearingedge
@svincent

**Comment by IanDCarroll** [comment]
Merge! Make a map website of local LA meetups that works and stuff!

Solved problems with geoJSON data undefined on the map.

Learned git commands, command line stuff, and general goings on
We also leaned to question our assumptions regarding what we think we know. Actually check, it'll save us time. :smile: 
Now script points to the right properties.

https://github.com/fullstackla/pairing-meetup/pull/72
@IanDCarroll
@caseytherocket
@thebearingedge

**Comment by machikoyasuda** [comment]
@IanDCarroll what is the URL to get to this map?

**Comment by IanDCarroll** [comment]
Well... 
I used gh-pages on my own repo to make it live. https://iandcarroll.github.io/fsla/ 

It might need to become it's own fullstackla repo with its own gh-pages branch if you want to use it in official production for fullstackla.

**Comment by gr2m** [comment]
Outreachy deadline is October 17. August 22 is deadline for sponsors

**Comment by jdorfman** [comment]
Great work @IanDCarroll

**Comment by IanDCarroll** [comment]
A chronicle of @caseytherocket, @thebearingedge and my pairing that serves as review and retro. Good work was done and valuable lessons learned :mortar_board: :dart: :+1: 

http://developingian.com/pairing-on-a-map-page/

**Comment by thebearingedge** [comment]
Haha @IanDCarroll awesome, even a post-game blog article. Rad!
