### ISSUE TITLE
Scheduled: Sep. 21st - talk about Falcor/Mapillary/etc. 

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#73]

**Comment by machikoyasuda** [comment]
hi @gyllen!!!!

**Comment by gyllen** [comment]
Hey @machikoyasuda

**Comment by gyllen** [comment]
@machikoyasuda Most of the weekdays in September works for me.

**Comment by machikoyasuda** [comment]
@gyllen How is September 21st, Wednesday? 7th is great too. :)

**Comment by gyllen** [comment]
Yeah works for me!

**Comment by kennethlee** [comment]
I'm super interested in this. Looking forward to it

**Comment by gyllen** [comment]
Also I meant the 21st... Let me know about specific times and also what you need from me in terms of presentation description.

Looking forward!

**Comment by machikoyasuda** [comment]
Canceled talk for now
