### ISSUE TITLE
Wed. Aug. 24th ⚡ 📻  the Show Notes 

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#74]
The next episode of FullStackLA live is here, with @kpearson & @machikoyasuda, brought to you by @MaxCDN / [StackPath](https://www.stackpath.com/) - thanks to our favorite @jdorfman :octocat: 

This week, we have a special local guest, developer & OSS contributor @eirinikos of Los Angeles, a local @homebrew 🍻  💎  contributor in the Ruby language. She will be talking about her summer as a fellow for Outreachy. 
### The local meetup forecast ☀️ ⛅
- **Event Pick of the Month**: 8th Light: SCNA, apply for the scholarship for their conference coming up at USC in October: http://scna.softwarecraftsmanship.com/opportunity/ 
- **Chat Guest**: Our virtual mentor of the night will be @gr2m. You can chat with him via Slack. Start here: http://hood.ie/chat/
- _Anything else to add?_ Add a link in the comments.
### Tonight's show
- 7 🕖  Stand Up
- 8 🕗  **Talk** on Homebrew by @eirinikos https://github.com/fullstackla/pairing-meetup/issues/62
- ✨  Pairing Time ✨ 
- 9 🕘   And there's always more for the hungry folks! Poquito Mas.js @ Poquito Mas 🍴
### A word from our sponsors:
- @MaxCDN is now StackPath. 
### Upcoming
- September edition of Fullstack: We will have local developer & OSS contributor @gyllen from @mapillary, speaking about @Netflix's library, Falcor. Netflix. Ever heard of it? 📺  Got any burning questions for @gyllen already about it? Get in on the discussion here: https://github.com/fullstackla/pairing-meetup/issues/73

Over and out ⚡

**Comment by benjaminma** [comment]
+1 @benjaminma HTML/CSS/JavaScript

**Comment by ghost** [comment]
@lenkli67 Ruby/ JavaScript/ HTML/ CSS

**Comment by kennethlee** [comment]
@kennethlee da Jay Ess.

**Comment by thomasjinlo** [comment]
@thomasjinlo Ruby

**Comment by leighphan** [comment]
+1 @leighphan HTML, CSS, JavaScript

**Comment by gnublet** [comment]
Python, R, C++, (maybe Java, HTML/CSS)

**Comment by dmacstack** [comment]
@dmacstack Ruby, PHP, JavaScript, HTML, CSS

**Comment by drmjo** [comment]
Majan ... PHP, JS ... never done ruby ... but i am down to learn...!!

**Comment by xuhdev** [comment]
+1 @xuhdev Python / HTML / CSS / C++

**Comment by gargruth2** [comment]
Swift, Objective-C

**Comment by jaimemendozadev** [comment]
@jaimemendozadev and I can do either Ruby or JavaScript ( probably 😉 )

**Comment by jdorfman** [comment]
@jdorfman | `markdown` `json` | https://github.com/jdorfman/awesome-json-datasets/issues/12

**Comment by IanDCarroll** [comment]
@IanDCarroll HTML/CSS/JS, Python, whatever

**Comment by IanDCarroll** [comment]
@xuhdev would like to share a tool he uses with firefox: Vimperator: http://www.vimperator.org/vimperator

Also, a rad blog about open source: https://www.topbug.net/blog/2016/08/19/why-is-open-source-beneficial-for-economic-growth-in-the-long-run/

**Comment by server-monitor** [comment]
Michael @server-monitor bash, Ruby, Perl, JavaScript, Python, HTML, CSS, would like to learn more Elixir and Go.

**Comment by machikoyasuda** [comment]
@IanDCarroll idea: maybe one day we can convert these show notes into "Awesome lists"

**Comment by IanDCarroll** [comment]
"Awesome lists?" I do not understand awesome. Can you explain it?

Also: another contribution: @xuhdev wrote about pairing on the map project: https://www.topbug.net/blog/2016/08/27/optimization-for-mobile-a-pair-programming-story-at-fullstackla/

**Comment by machikoyasuda** [comment]
@IanDCarroll https://github.com/sindresorhus/awesome
