### ISSUE TITLE
2016 Winter Talk: Scheduled - 🍂 Nov 2 - Justin Dorfman on Awesome lists, autorunning tests on PRs

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#75]
@jdorfman 

Talk inspiration:

I, Machiko, grew up writing on and for the internet. It started with Notepad, Expages and later led to working on the college newspaper. It took me all the way to the Washington Post writing headlines into a custom CMS (Content Management System). It was hard to keep basic internet HTML up to date: Links die, articles get out of date, versions get updated, and text can be hard to search if you use two different spellings or abbreviations. I would do all this web producing work, and then, 2 years later, when someone asked me about it, the page was littered with broken links. 

What can we do about it? Having strict style guide rules, like Awesome rules, can help. But sometimes, being an editor, you feel bad for being so nitpicky on someone else's writing, or you get lazy to edit your own writing.

Enter awesome rules and github hook tools:

@jdorfman - advocate for open source maintainers all over the world - will discuss how he uses open source tools to keep his open source lists up to date, complete with an Awesome badge.

**Comment by jdorfman** [comment]
`s/talk/lightning talk/g`

**Comment by jdorfman** [comment]
@machikoyasuda what date were you thinking?

**Comment by machikoyasuda** [comment]
Options:
- [ ] September 21
- [ ] October 5
- [ ] October 19
- [x] November 2 (After AllThingsOpen)

**Comment by machikoyasuda** [comment]
Once we set a date, I will start inviting "people who do use tools like GitHub, command line" to "write awesome lists"... for e-mail newsletters, documentation, blogs, etc. :) ✏️

**Comment by jdorfman** [comment]
- November 2 (After AllThingsOpen)

Would be ideal =)

**Comment by machikoyasuda** [comment]
🏁 🏁 November 2 it is!

**Comment by jdorfman** [comment]
Preview:

![image](https://cloud.githubusercontent.com/assets/398230/17990093/83ad71dc-6ae7-11e6-8a7e-f1be61b5be09.png)

**Comment by machikoyasuda** [comment]
I caught a sneak peek of the Unit Testing for Writing episode and I cannot wait until it comes out live, November 2. Wowowow!

**Comment by IanDCarroll** [comment]
Ooh! I will be looking forward to this!

**Comment by machikoyasuda** [comment]
@jdorfman Ready for Nov 2?? Or should we do an Arduino demo instead??

**Comment by jdorfman** [comment]
@machikoyasuda totally dropped the ball on this. Personally I think Arduino would better. I will do a 2-3 min lightning talk/pitch on what we can do with Javascript & hardware.

**Comment by jdorfman** [comment]
@machikoyasuda 

![image](https://cloud.githubusercontent.com/assets/398230/19826913/a30748f4-9d4c-11e6-85b3-59c0e780271b.png)

@IanDCarroll and I are hard at work

**Comment by machikoyasuda** [comment]
⚡️ Talk <3

I'm gonna do a 2-3 min talk after you on switching to using OSS platforms :)

**Comment by jdorfman** [comment]
@machikoyasuda sounds awesome. I promise @IanDCarroll and I won't disappoint!
