### ISSUE TITLE
Know a bit of HTML/CSS/JS? Some issues for you to work on.

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#77]
I am going to start a list of open source websites that @fullstackla <3s that have GitHub issues for people who want to make websites more usable and beautiful by editing HTML/CSS:
- OpenStreetMap.com website: https://github.com/openstreetmap/openstreetmap-website/issues - I use this site to add/edit things. For example, when I moved to a neighborhood - I noticed a blue sign on the street that said "Del Rey." But when I looked my house up on Apple Maps, the neighborhood said DEL RAY. I changed it: https://www.openstreetmap.org/changeset/21637352
  ![screenshot 2016-08-25 16 55 01](https://cloud.githubusercontent.com/assets/3673236/17989777/b02093c8-6ae4-11e6-9bfe-a3ac16a50772.png)

I did think, though, that this website was a little hard to use. We could give them a few PRs!

**Comment by machikoyasuda** [comment]
On the horizon @IanDCarroll 🌅

**Comment by IanDCarroll** [comment]
Here's a list of issues on our fsla map page: https://github.com/IanDCarroll/fsla/milestone/1

Issue buffet! Take what you like! 

New devs welcome!!! Scroll down to our README.md to get your bearings: https://github.com/IanDCarroll/fsla
