### ISSUE TITLE
First Timers  🏰 On your way to FullStack

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#78]
First time contributors?

Welcome to FullStack!

If you signed up for a GitHub account and made it this far, kudos! 

You can post your questions here and we will answer them to the best of our abilities.

**Comment by machikoyasuda** [comment]
Questions about parking should go here cc @IanDCarroll 
- MaxCDN, now part of StackPath, is located in a building near Universal Studios & Hogwarts School fo Wizardry, off Cahuenga. We will provide free parking validation if you park inside the building. There is also metered spots along both sides of Cahuenga.
- Food nearby: InnOut, Poquito Mas
- Post any other meetup tips here

**Comment by IanDCarroll** [comment]
# How to Park

_full validation provided_

![20160824_181106](https://cloud.githubusercontent.com/assets/14797009/17991269/ef63906e-6af1-11e6-96a1-78a27eb7fce4.jpg)
![20160824_180414](https://cloud.githubusercontent.com/assets/14797009/17991316/508e2610-6af2-11e6-86eb-6b719badc58b.jpg)
![20160824_180355](https://cloud.githubusercontent.com/assets/14797009/17991364/9f76202a-6af2-11e6-9dea-388a0bd8fddb.jpg)
![20160824_180234](https://cloud.githubusercontent.com/assets/14797009/17991380/ec789f24-6af2-11e6-944e-7e9dd8370a1d.jpg)
![20160824_180119](https://cloud.githubusercontent.com/assets/14797009/17991412/5b127662-6af3-11e6-9fce-4a49aeac71dc.jpg)
![20160824_180046](https://cloud.githubusercontent.com/assets/14797009/17991468/c830d16c-6af3-11e6-9dcd-33343db38ef7.jpg)
![20160824_181829](https://cloud.githubusercontent.com/assets/14797009/17991494/1f8da188-6af4-11e6-8a29-bda1c0f0268d.jpg)

**Comment by IanDCarroll** [comment]
# How to Walk

_validation unavailable, but we still think you're valid!_

![20160824_181106](https://cloud.githubusercontent.com/assets/14797009/17991719/0a1813f4-6af6-11e6-9daf-79d1dfbf979e.jpg)
![20160824_181735](https://cloud.githubusercontent.com/assets/14797009/17991744/54e525e8-6af6-11e6-86f1-7a27f0df4b0c.jpg)
![20160824_181745](https://cloud.githubusercontent.com/assets/14797009/17991795/bb7ee9b0-6af6-11e6-8ea7-c84d3a46bfbc.jpg)
![20160824_181805](https://cloud.githubusercontent.com/assets/14797009/17991810/f02475c2-6af6-11e6-8921-ae64e56d421c.jpg)
![20160824_180046](https://cloud.githubusercontent.com/assets/14797009/17991862/4d4b73b8-6af7-11e6-8994-17ec379614ba.jpg)
![20160824_181829](https://cloud.githubusercontent.com/assets/14797009/17991910/94e74210-6af7-11e6-8dbd-a4c88965f662.jpg)

**Comment by machikoyasuda** [comment]
Closing b/c we have a new space now <3
