### ISSUE TITLE
2017 January: Pair Interview Practice

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#79]
Practice for programming job interviews in pairs and learn from the pros - the people who are interviewing. 
### Brainstorming:
- Software engineers experienced in teaching interviewing can give us tips to practice: @ssebelius
- Whiteboard practice: learn an algorithm or a popular interview question (the kind they test you on), study it. Bring it to the meetup and practice explaining it on the white board.
- Skype practice: learn how to set up your home Skype situation better so you have good lighting, good sound. Practice talking about code out loud to a screen in front of you. Practice talking to people over Skype/Hangouts. Learn all the ways to debug those pesky audio problems.
- Code challenge practice: Practice popular code katas for interviews in pairs.
- Interview each other.
- Resume/LinkedIn/website portfolio critiques. I love editing resumes. I A/B test my resumes. 
### Needs:
- [ ] Date
- [ ] Location that can handle lots of talking
### Discussion:

Have you interviewed in the SoCal area for a developer job recently? What kind of format and kind of questions did you get? We would love to hear about your experiences to see what kinds of interview styles we can practice in pairs.

**Comment by machikoyasuda** [comment]
@IanDCarroll what do you think? :)

**Comment by IanDCarroll** [comment]
@machikoyasuda Sounds like a thing to do and a thing I'd want to participate in/help make happen!

**Comment by IanDCarroll** [comment]
I'll start scouting locations

**Comment by IanDCarroll** [comment]
Location Requirements:
- Can handle talking
- Has access to a white board
- Has capacity for up to 30 people
- Has available power outlets

Missing anything?

**Comment by machikoyasuda** [comment]
@kangashley you might wanna heads up on this too :) this could be a fun way to practice talking about algorithms/common programming questions. it is also a great way to share what kinds of questions y'all have been getting in interviews lately.

**Comment by machikoyasuda** [comment]
@IanDCarroll do you still wanna do this sometime? should we schedule a date?

**Comment by IanDCarroll** [comment]
@machikoyasuda I got stuck thinking of a decent location. The only solution I came up with is the second floor of the Glendale Barnes and Noble where I work. I don't have much prepared besides that.

**Comment by machikoyasuda** [comment]
@IanDCarroll what about 8th Light? we can help with logistics (1. finding location, 2. making an invite on meetup, 3. outreach/marketing) and you can run the show of the day-of content/schedule/organizing, etc.

**Comment by IanDCarroll** [comment]
@machikoyasuda That would definitely work well. They have a much better space.

For the show, I can prepare some common questions via google. But I don't know all the dimensions of an interview. You've mentioned setting up a laptop to give good lighting for skype screening interviews. Would you be interested in giving a 15 minute talk on aspects of interviews besides coding challenges with whiteboards?

As for questions that people have encountered recently, we can do 5 minute lightening talks, or discussion topics based on what people write on and vote with post-its. That seems to work well when I've seen it applied.

**Comment by IanDCarroll** [comment]
As for a date, as we get closer to December, my ability to set aside time that work won't schedule me becomes slim to none. It might be a good idea to do this in January, if that's not too far away.

**Comment by machikoyasuda** [comment]
Moving this forward to 2017 when people are less busy.
