### ISSUE TITLE
Beginner's Guide to Preparing for Pair Programming Night

### ISSUE THREAD

**Issue by kennethlee** [fullstackla/pairing-meetup#8]
## Welcome to Eastside Pair Programming Night!

Hello, and welcome to Pair Programming Night! We're excited you could join us.

This guide is intended to bring neophytes up to speed so that they may hit the ground running come meetup night.

---
##### What is Pair Programming?

Two programmers sit side-by-side in front of one computer. One person takes the role of the driver (the person doing the typing) while the other assumes the role of the navigator (the person focusing more on directing the flow of the work). Both, however, are actively engaged in the programming process, and the pair will switch roles at a given interval of time (usually a few minutes) or at a convenient/natural stopping point.

For more information, you may find a helpful infographic [here](http://www.londonacademyofit.co.uk/learning-blog/learning/psychology-of-pair-programming-infographic/) (kudos to Machiko for finding this nifty page) and the Wikipedia entry for pair programming [here](https://en.wikipedia.org/wiki/Pair_programming).
##### What is TDD?

In a nutshell, [Test-Driven Development (TDD)](http://agiledata.org/essays/tdd.html) is an iterative approach to software development whereby:

1) The test code is written first
2) Just enough production code is written to make the test pass
3) The production code is then [refactored](https://en.wikipedia.org/wiki/Code_refactoring) as necessary
4) Repeat steps 1-3, ad infinitum

---
##### Text Editor

You will need a text editor with which to write your code. Below are a few popular options:
- [Atom](https://atom.io/)
- [Sublime Text](http://www.sublimetext.com/2)

---
##### The Command Line

Familiarizing yourself with the shell of your OS platform would be prudent. Check out Zed Shaw's straightforward [crash course](http://cli.learncodethehardway.org/book/) to get yourself started.
##### Ruby

If you would like to work with the Ruby programming language, you may find [this step-by-step installation guide](http://guides.railsgirls.com/install/) helpful.

Fin.

**Comment by machikoyasuda** [comment]
I decided to put this in the Wiki: https://github.com/machikoyasuda/dtla-pair-programming/wiki/Onboarding

Can you edit the Wiki @kennethlee? Please feel free to add/edit.

Screenshots might be nice.

**Comment by machikoyasuda** [comment]
@kennethlee https://github.com/machikoyasuda/dtla-pair-programming/wiki !!

**Comment by kennethlee** [comment]
@machikoyasuda Yep, looks like I am able to edit the Wiki :+1:
