### ISSUE TITLE
Winter Talk idea: Using and "dog-fooding" open source & open data everything

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#82]
- Instead of Google Maps, maps.me and OpenStreetMaps data
- Instead of Evernote, Notational Velocity
- Instead of Google Hangouts, https://jitsi.org/Projects/JitsiMeet
- Instead of your favorite chat app, https://telegram.org/
- Instead of your favorite desktop mail client, Thunderbird
- Instead of ArcGIS, QGIS
- Instead of whatever else, https://prosody.im/
- Instead of SublimeText, Atom
- Hosting your own data/servers: https://sandstorm.io
- Contribute data to Wikipedia, OpenStreetMaps

The idea is two-fold:
1. Find open source alternative to your favorite proprietary tool to use
2. Find a open source alternative to your favorite proprietary tool to use _and to improve & contribute to_

**Comment by machikoyasuda** [comment]
https://www.topbug.net/blog/2016/09/13/how-to-achieve-different-open-source-levels-on-your-laptop-desktop/

**Comment by xuhdev** [comment]
https://prism-break.org/en/all/

**Comment by machikoyasuda** [comment]
@xuhdev we should contribute to this list to make it even more meta :) https://github.com/nylira/prism-break/blob/master/CONTRIBUTING.md

**Comment by xuhdev** [comment]
@machikoyasuda Yep, for example, they don't have QGIS listed yet...

**Comment by machikoyasuda** [comment]
@xuhdev you read my mind! hah.
