### ISSUE TITLE
2017 Talk idea: How to PGP and other security topics

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#84]
- OpenSSL
- Open SSH
- Bitcoin
- Other fun topics.. Lightning round talks of random open source projects we wanna learn out about.

**Comment by machikoyasuda** [comment]
- OpenSSL
- Open SSH

**Comment by machikoyasuda** [comment]
@kangashley i am putting you here :) can you link me to your pgp project notes here?

**Comment by kangashley** [comment]
[Here](https://paper.dropbox.com/doc/Planning-PGP-talkdemo-7rMPKaG7VnElgF5kVN8xa) you go! Major inspiration was the [Encryption Works](https://github.com/freedomofpress/encryption-works/blob/master/encryption_works.md) guide by Freedom of the Press.

**Comment by machikoyasuda** [comment]
@kangashley can you save these Paper things into Markdown files on github instead? or gist? it is easier to edit, fork, share, collaborate with on others. it is a faster, less proprietary format!

**Comment by thewillhuang** [comment]
another really interesting topic is https://github.com/WhisperSystems/libsignal-protocol-javascript its an open source security protocal being used by google facebook and many others to do perfect forward secrecy, i thought it would be related :D
