### ISSUE TITLE
Ideas for small projects that can be pair programmed

### ISSUE THREAD

**Issue by xuhdev** [fullstackla/pairing-meetup#85]
These projects can be really tiny but still are real contributions. Perhaps it's a good idea to make a wiki page to maintain this list? 
- [AUR (ArchLinux User Repository) packages](https://aur.archlinux.org/packages/)
- [bash auto completion scripts](https://github.com/scop/bash-completion)
- [el-get recipes](https://github.com/dimitri/el-get/tree/master/recipes)
- [homebrew recipes](https://github.com/Homebrew/homebrew-core/tree/master/Formula)
- [pygments lexers](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/)
- [zsh auto completion scripts](https://github.com/zsh-users/zsh-completions)

**Comment by machikoyasuda** [comment]
👍🏽👍🏽
Can anyone start a wiki page in this repository's wiki? Or do they need admin permission? @kitpearson wanna start one?
I am away-from-computer till 9/16. 

```
    _____________________________
```

**Comment by machikoyasuda** [comment]
oops. @kpearson. 

On Thu, Sep 8, 2016 at 5:47 PM +0900, "Machiko Yasuda" machikoyasuda@gmail.com wrote:

```
    👍🏽👍🏽
```

Can anyone start a wiki page in this repository's wiki? Or do they need admin permission? @kitpearson wanna start one?
I am away-from-computer till 9/16. 

```
    _____________________________
```

**Comment by xuhdev** [comment]
It turns out that I can create wiki pages. Now available [here](https://github.com/fullstackla/pairing-meetup/wiki/Ideas-for-small-projects-that-can-be-pair-programmed).
