### ISSUE TITLE
News update: You don't need a gh-pages branch to deploy gh-pages

### ISSUE THREAD

**Issue by IanDCarroll** [fullstackla/pairing-meetup#86]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

You have 3 options in settings:
1. You can use a gh-pages branch to deploy your page. This creates problems, because you have to keep merging from master, or your master and gh-pages branches start getting wonky and out-of-sync.
2. You can also just use master as your gh-pages deploy reference. This means you only have to keep one branch for your repo! Ah, the simplicity!
3. If you need a gh-pages site to support the non-static-website thing you're working on, you can load all the static website stuff into a doc folder on the master branch, and GitHub knows to deploy just that. which is very neat and tidy if you want a pretty web page to attract contributors to you project!

With options 2 and 3, I am having a hard time finding a justification to keep a gh-pages branch at all any more. But horray for more better usefulness!

**Comment by machikoyasuda** [comment]
@IanDCarroll This is awesome. Can you move this to a wiki page instead? Issues should be for issues, we can use Wiki for help/documentation/lists of links.
