### ISSUE TITLE
9/21 ⚡ 📻   Show Notes: Talk with Josh Cheek

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#89]
# Announcements
- Thanks to our sponsor @8thLight
# Talk:
- Summary:  Forking a repo, running tests, fixing tests and pushing it up
- The instructions: https://gist.github.com/JoshCheek/9c00965885785daf03a7015799ee5722
- The repository we forked: https://github.com/JoshCheek/erroneous_creatures
- The forked repositories: https://github.com/JoshCheek/erroneous_creatures/network/members
- The pull requests: https://github.com/JoshCheek/erroneous_creatures/pulls
  # Attendees
1. \- @kpearson 
2. \- @server-monitor
3. \- @jdorfman
4. \- @thomasjinlo
5. \- @dcmoore from @8thlight
6. \- @gr2m from @hoodiehq
7. \- @jaimemendozadev 
8. \- @xuhdev
9. \- @anymoto
10. \- @gnublet
11. \- @jkuchGit
12. \- @machikoyasuda
13. \- @colin-m-b
14. \- @aarboleda1

**Comment by thomasjinlo** [comment]
@machikoyasuda do you happen to remember what the code was for the SCNA discount?

**Comment by dcmoore** [comment]
LA-MEETUP

**Comment by gr2m** [comment]
The ticket for http://scna.softwarecraftsmanship.org/ with the LA-MEETUP access key, do you know if it includes the Code Retreat? Because that’s what I’m most interested in :)

**Comment by IanDCarroll** [comment]
@gr2m Apparently it does, but I'm not sure if it includes you automatically. You might need to send them an e-mail or a message to double check if every LA-MEETUP is automatically included, or we each need to contact the hosts to go in manually and make it so.

![conversation](https://cloud.githubusercontent.com/assets/14797009/18810157/cff69316-8243-11e6-884e-12ab7a8badde.png)

cc/ @dcmoore
