### ISSUE TITLE
Next meetup: RNA Transcription - Discuss organizing code into classes, etc.

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#9]
## Stuff to Highlight
- Compile and highlight all the recent useful nitpicks from people's exercisms, 
- Compile and highlight new or interesting methods, patterns. Ask people to present something new they've used and learned.
- **Code Demo** - highlight a CodePen/Gist example that people can try out too
## JavaScript
- @ashwell - http://exercism.io/submissions/956786105e1349ffa31b4381caa1e2b9?i=1
- @machikoyasuda - http://exercism.io/submissions/dff3251268be4aba8f5aa4ebadfaea2c
- @enddynayn - http://exercism.io/submissions/008ed5cf41fb494e825eb65f402f14f8
- **example** - https://github.com/exercism/xjavascript/blob/master/rna-transcription/example.js

Note: JavaScript test suite does not include raising an argument if a strand is not a valid DNA or RNA.
## Ruby
- @kgabinete08 - http://exercism.io/submissions/c9c34a32eed34474b617e4e215b87cb6
  methods used: `chars`, `each`, `include?`, `invert`, `<<`, constant in class, 2 public methods
- @kennethlee - http://exercism.io/submissions/10c2d8eab99c454da6b426603338b578
  methods used: `chars`, `each`, `has_key?`, `invert`, `select`, `push`, `join`, constant in module, 2 public methods
- @rebelwarrior - http://exercism.io/submissions/90a59c8da306411d8b23f6181753b0d8
  methods used: `each_char`, `map`, `fetch`, `join`, private method, 2 public methods, class variable
- **example** - https://github.com/exercism/xruby/blob/master/rna-transcription/example.rb
  methods used: `tr`, `chars`, `map`, creates `DNA` and `RNA` class for the `ArgumentError`

Are there any good websites/blog posts that discuss for either Ruby or JS, how to refactor code by better organizing code into classes, private/public methods, modules, etc?

**Comment by rebelwarrior** [comment]
There is a great book for ruby called Practical Object Oriented Design in Ruby by Sandy Metz. 

```
 On Tuesday, October 27, 2015 2:53 PM, Machiko Yasuda <notifications@github.com> wrote:
```
- JavaScript  
  @ashwell - http://exercism.io/submissions/4911554777bb4e7f82405c92e77d8626  
  @machikoyasuda - http://exercism.io/submissions/fc712a56e8e54076b15b145219c8885d
- Ruby  
  @kennethlee - http://exercism.io/submissions/10c2d8eab99c454da6b426603338b578  
  @rebelwarrior - http://exercism.io/submissions/90a59c8da306411d8b23f6181753b0d8
  Are there any good websites/blog posts that discuss for either Ruby or JS, how to refactor code by better organizing code into classes, private/public methods, modules, etc? —

**Comment by machikoyasuda** [comment]
hi @rebelwarrior :) I have that book and I just started it! I will use it to figure out a mini-lesson for the next meetup. 

ps. you are the #1 exercism warrior on our team.

pps. come out to the next meet-up! next week, not this week.

**Comment by kennethlee** [comment]
A discussion about code organization is a great idea!

On Tue, Oct 27, 2015 at 11:58 AM, Machiko Yasuda <notifications@github.com (mailto:notifications@github.com)> wrote:
> hi @rebelwarrior (https://github.com/rebelwarrior) :) I have that book and I just started it! I will use it to figure out a mini-lesson for the next meetup.  
> ps. you are the #1 (https://github.com/machikoyasuda/dtla-pair-programming/issues/1) exercism warrior on our team.
> pps. come out to the next meet-up! next week, not this week.
>  
> —
> Reply to this email directly or view it on GitHub (https://github.com/machikoyasuda/dtla-pair-programming/issues/9#issuecomment-151610184).
>  
>  
>  
>  
>  
>  





--  
Kenny Lee
(909) 263-3497
GitHub (https://github.com/kennethlee)
