### ISSUE TITLE
Start PULL_REQUEST_TEMPLATE.md and ISSUE_TEMPLATE.md, PULL_REQUEST_EXAMPLES.md.

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#93]
- Teach people how to make PR
- Teach people how to write a solid PR message, with the Fullstack logo :)

**Comment by IanDCarroll** [comment]
Are we talking about some documentation or a workshop?

**Comment by machikoyasuda** [comment]
As a meetup organizer, I want to have written and verbal instructions for attendees at every meetup on how to make a Pull Request with a `Made at Fullstack` link, so that we can more easily track every PR/Issue created at our meetups.

**Comment by IanDCarroll** [comment]
Ok, can I claim this?

I think it'd be good if a diagram was involved.
questions:
1. Should it be like a poster?
2. we'll need specific instructions on that logo and link. What is it linking to?

**Comment by machikoyasuda** [comment]
Our MVP (minimum viable product) for now can be something like: 

### Code:

```
---

[Made at Fullstack LA](https://meetup.com/la-fullstack/events/234620974) :zap:
```

---

### What it looks like:

[Made at Fullstack LA](https://meetup.com/la-fullstack/events/234620974) :zap:

Inspired by https://github.com/devspace/awesome-github-templates/blob/master/readme.md these issue and PR templates. We can make a PR/Issue template for us :)

**Comment by machikoyasuda** [comment]
@IanDCarroll maybe...
1. You could make a PULL_REQUEST_TEMPLATE.MD and ISSUE.MD, with the code above.
2. Then you could will make a PULL_REQUEST_EXAMPLES.MD and ISSUES_EXAMPLES.MD list, with links to PRs you and other fullstackers have made as good examples to follow. Practices like: adding instructions on how to replicate bug/issue, relevant URLs, screenshots, explaining..etc.. would be great to highlight and keep forever.

**Comment by IanDCarroll** [comment]
Ok, sounds good. I'll get to work on these. Is there a deadline you need them by?

**Comment by machikoyasuda** [comment]
by next Wednesday!? we can work on finishing it + announcing it next wed.

**Comment by IanDCarroll** [comment]
Ok, I'll have it before then :)

**Comment by IanDCarroll** [comment]
Can I get some shout outs from people who have seen good pull requests to put in the example files?
(Of course these examples will not have the same templating...)

**Comment by machikoyasuda** [comment]
@IanDCarroll  here are some PRs from fullstack peoples
https://github.com/Pinwheeler/Parrit/pull/40
https://github.com/Pinwheeler/Parrit/pull/39
https://github.com/hoodiehq/hoodie-camp-tutorial/pull/19
https://github.com/hoodiehq/hoodie-camp-tutorial/pull/22
https://github.com/hoodiehq/hoodie-camp-tutorial/pull/22

**Comment by IanDCarroll** [comment]
Alright, just going to copy-paste this last set of examples into a .md, and then that's a first pass attempt at this :+1:
