### ISSUE TITLE
Suggest a different entry level editor?

### ISSUE THREAD

**Issue by xuhdev** [fullstackla/pairing-meetup#94]
Currently atom is the suggested editor, but there is a privacy issue associated with it -- it sends data to Google analytics by default: https://atom.io/faq#why-does-atom-send-usage-data-to-google-analytics

Here are my suggestions: (all of them work are easy to get hands on and have descent programming features out of the box)
- Windows: Notepad++
- macOS: Textmate
- GNU/Linux and *BSD: geany

**Comment by server-monitor** [comment]
Linux (going from easiest to hardest to work with): gedit (the notepad of Gnome-Linux), Sublime Text 3, emacs, vi/vim/gvim.

**Comment by ashwell** [comment]
Sublime might be a good choice, but I feel like emacs and vim are no-nos. Don't get me wrong, I love my vim setup and can't program at speed without it anymore but for someone starting out, just learning how to program is enough of a challenge. Adding the complexity of vim is just plain mean.

...

[![](https://imgs.xkcd.com/comics/real_programmers.png)](https://xkcd.com/378/)

**Comment by IanDCarroll** [comment]
Personally, does it matter all that much? If you are new and it's your first editor, are you really writing stuff that needs to be that secure? Here's the data atom collects: https://github.com/atom/metrics I suppose those shopping for a good starter editor should be aware of that, but if it were me, I'd be fine using it.

**Comment by server-monitor** [comment]
Maybe some people are more attuned to how vi or emacs work. You never know. ;)

**Comment by kennethlee** [comment]
I'm with @ashwell; Sublime is a good choice (and cross platform). Emacs/vim shouldn't really be a part of this discussion at all, in my opinion.

**Comment by xuhdev** [comment]
I'm against sublime text since an open source meetup should not normally recommend a proprietary product -- many good open-source contributions are discovered in daily use, and sublime text, as a proprietary product, destroys a lot of possible contributions.

**Comment by gnublet** [comment]
Could we try to make a text editor from scratch?

**Comment by machikoyasuda** [comment]
i love this thread.

@xuhdev thanks for bringing this up. i never knew about this Metrics package. 

@IanDCarroll thanks for looking up information about the package. i read in the README that there is an option to disable the Metrics package, and i just did that. not too hard to disable.

![screenshot 2016-10-13 15 02 37](https://cloud.githubusercontent.com/assets/3673236/19368889/2c5093d8-9157-11e6-9819-4916fae675a3.png)
![screenshot 2016-10-13 15 02 56](https://cloud.githubusercontent.com/assets/3673236/19368891/2c57fb8c-9157-11e6-941a-65c99fe2a363.png)
![screenshot 2016-10-13 15 03 00](https://cloud.githubusercontent.com/assets/3673236/19368890/2c566d30-9157-11e6-9382-3578778280ab.png)

@gnublet 😅 😆 

for anyone: 

In our README.md, feel free to 1) add instructions to disable Metrics package, 2) add links to other free & open source code editors you like, esp. for Linux and Windows. emphasis on free & open source, so no Sublime Text! 

I would like everyone to know I just switched my default browser from Chrome to Firefox to write this message. :)

**Comment by xuhdev** [comment]
@machikoyasuda  Thanks for the instructions (and glad you switched browser)!

Sorry about the outdated info about Atom: the most recent release (2 days ago) uses an "opt-in" scheme rather than the past "opt-out" scheme atom/atom#4966 : https://github.com/atom/atom/releases/tag/v1.11.0

So IMO this issue is no longer valid.

**Comment by gr2m** [comment]
I think it’s a good idea to offer different choices with short explanations why, but we also should make a recommendation, because people new to coding are looking for advise. 

I think the most recent Atom editor no longer send this data by default, it is opt-in, but we should double check. 

I think Atom is a great Editor to suggest, because it is hackable with technologies that are widely known and documented, while most other editors have their own custom language to write extensions.
