### ISSUE TITLE
An app to celebrate PRs created during events

### ISSUE THREAD

**Issue by gr2m** [fullstackla/pairing-meetup#99]
#### 🤔💭 User Story

As a meetup organizer,
I want to make everyone's pull requests visible to everyone as they happen,
so that that we can celebrate together :).
#### 😫😪 Current Behavior

We try to manually keep track of attendees and their pull requests. For example see this issue: https://github.com/fullstackla/pairing-meetup/issues/92
#### 🎯💡 Idea

The first thing that comes to mind is a web app where we can create an event with a start / end time and then add all the attendees’ github profiles. While the event is going, we monitor contributions of all accounts. The moment someone starts a PR it could show up in a list or something. To make it funnier it could have sound / visual effects and we could show that at all times during the event.

Even cooler would be a piece of hardware like a bell or an alarm that goes off everytime a PR is started :) So this could become a small hardware project later \o/

**Comment by machikoyasuda** [comment]
I'm really into the hardware 💡 ⚡️ part (!!)

**Comment by machikoyasuda** [comment]
@jdorfman @IanDCarroll Are you gonna bring an Arduino to next week to the next Fullstack?

**Comment by jdorfman** [comment]
@machikoyasuda oh yeah, I will be adding lessons to https://github.com/jdorfman/arduino-basics as well and would like to pair with @IanDCarroll on writing them.

**Comment by jdorfman** [comment]
@machikoyasuda the idea is anyone can hook up my Arduino to their laptop and if they like it, then they can get their own and bring it to the next meetup

**Comment by jdorfman** [comment]
@gr2m I could use your help with the GitHub API...

**Comment by IanDCarroll** [comment]
@jdorfman do you want to start pairing on this at the meetup? or meet ahead of time so we have something to show?

**Comment by jdorfman** [comment]
ahead of time would be great. I get home tonight from NC but Friday, Sunday, Monday @ night work. Plus you have Ubuntu so I want to make sure we can get this setup before.

**Comment by IanDCarroll** [comment]
@jdorfman I got all of Friday free and Saturday/Sunday evenings. We could take multiple sessions if need be. I'd like to have something ready to rock by show time. 

Any ahead of time solo prep I can do to get up to speed more quickly for the session(s)?

**Comment by gr2m** [comment]
@jdorfman happy to help with the GitHub API :) I might hack a little service together that just works in-memory for the time of the event. If we could ping an arduino or sth similar via HTTP that’d be the simplest :)

Also instead of hacking the service together, might as well coach people to do it if anyone is interested. Here is how I would approach this roughly. This is not super elegant as it will pull data instead of using http hooks, but it’s simpler to build and we can still fancy it up later :) We can work in 3 teams: backend team, frontend team, hardware team. Backend / Frontend team should work on same repository.

### Step 1

#### Backend team
- [ ] build a hello world example app with [hapi](http://hapijs.com/)
- [ ] deploy to it [now](https://zeit.co/now/)

#### Frontend team

Make a static HTML page which allows us to set an event title, start / end time and that let’s us add attendees by their gh username. Store everything in localStorage for persistance. Put all assets into a `public/` folder in the repository

#### Hardware team

Figure out how we can ping a device over the local network :) something like `GET http://192.168.0.123/alarm` should ring a bell or something :)

### Step 2

#### Backend team
- [ ] add a route `GET /pull-requests/{username}` that returns JSON, can be hardcoded at first:

``` json
[
  { "title": "...", "url": "...", "nr": "...", "createdAt": "..." }
]
```
- [ ] server static files from the `public/` folder at `/*`. Create `public/index.html` file that loads `GET /pull-requests/gr2m` and displays the pull requests in a table

#### Frontend team

For each attendee, send `GET /pull-requests/{username}` in intervals and show the returned pull requests in a table :) 

### Step 3

#### Backend team:

in the `GET /pull-requests/{username}` route handler, load the PRs from the last 4 hours or so for the given user. There is an [API to list all pull requests by owner](https://developer.github.com/v3/pulls/#list-pull-requests), or  you can use the new [GraphQL API](https://developer.github.com/early-access/graphql/guides/accessing-graphql/) if you are fancy :) Coordinate with the front-end team if you need to change the JSON format for the response

#### Frontend team

Show all new PRs as they come in, sort them by time, newest on top. Also show when a PR got merged. 

Whenever a new PR gets started from one of the attendees or a PR gets merged, send a request to the hardware on the local network

#### Hardware team

Coordinate with frontend team

**Comment by IanDCarroll** [comment]
@gr2m Do we have the people/time resources to do all that by Wednesday?

**Comment by machikoyasuda** [comment]
@gr2m @IanDCarroll sounds like we got a great meetup plan for Wednesday. we can make backend teams, front end teams, teach how to use APIs, teach how to do the hardware stuff, teach ppl how to work agile in real life. ...!

**Comment by gr2m** [comment]
yeah I’d try to do it during a wednesday. We can prepare it ahead of time like creating a repository, creating the issues. We could also do some research for the hardware part because I don’t know how that will work, but it’s not required and can be added later

**Comment by server-monitor** [comment]
This is awesome. I'd love to join.
